### ISSUE TITLE
Minor comments on the installation instructions

### ISSUE THREAD

**Issue by nterhoeven** [Kinggerm/GetOrganelle#10]
Hi @Kinggerm 

we are currently working on a benchmarking of chloroplast assembly tools (see https://github.com/chloroExtractorTeam/benchmark). In this context, I installed GetOrganelle on a fresh installation of Ubuntu 18.04.2 and noticed a few things you might want to add to your installation instructions:

- pip and git are not installed by default
- the `GetOrganellePATH` directory has to be created first.
- it would be nice to have a test dataset, so I can check the functionality after installation

Best,

Niklas

**Comment by Kinggerm** [comment]
Hi Niklas,

Thanks a lot for the comments.
Looking forward to the benchmark test.

Best,
Jianjun

**Comment by Kinggerm** [comment]
Hi Niklas, 

I saw your latest manuscript (https://www.biorxiv.org/content/10.1101/665869v3.full) and found the mentioned issue of no test data. This is already solved but I forget to leave a msg here.

You can find a small test at homepage (https://github.com/Kinggerm/GetOrganelle#test) or more tests at GetOrganelle.wiki (https://github.com/Kinggerm/GetOrganelle/wiki/Examples) with both plastome and mitogenome assembly.

Best,
Jianjun
