### ISSUE TITLE
Fail in Disentangling stage

### ISSUE THREAD

**Issue by lstxmu** [Kinggerm/GetOrganelle#100]
HI , i try to ran getorganelle to assemble a plant cp geome. but fail in disentaling stage . can you help fixing the issue?
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7175822/get_org.log.txt)

**Comment by Kinggerm** [comment]
Do as what the log told you, check https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#what-should-i-do-with-incomplete-resultbroken-assembly-graph first

**Comment by Kinggerm** [comment]
I will temporarily close this issue for no further reply. Feel free to reopen it with further related information.
