### ISSUE TITLE
Please help me to run getorganelle

### ISSUE THREAD

**Issue by sabrtoothcat** [Kinggerm/GetOrganelle#103]
I got this error message: /var/spool/PBS/mom_priv/jobs/3745289.sched01.SC: line 17: get_organelle_from_reads.py: command not found

#!/bin/bash
#PBS -l select=1:ncpus=24:mpiprocs=24
#PBS -l walltime=24:00:00
#PBS -q serial
#PBS -P CBBI1133
#PBS -o /mnt/lustre/users/clee/outputs/getorganelle/getorganelle.out
#PBS -e /mnt/lustre/users/clee/outputs/getorganelle/getorganelle.err
#PBS -N getorganelle
#PBS -m abe
#PBS -M 4117560@myuwc.ac.za

module load chpc/BIOMODULES
module load get_organelle/1.5.2

cd /mnt/lustre/users/clee/outputs

get_organelle_from_reads.py -1 /home/clee/lustre/input/S1_L4_R1.fastq.gz -2 /home/clee/lustre/input/S1_L4_R2.fastq.gz -o mitochondria_output -R 50 -k 21,45,65,85,105 -P 1000000 -F embplant_m

Does anyone know what this means and how I can fix this so I can get it to run?

**Comment by Kinggerm** [comment]
1.5.2 is too old, maybe three years ago, which is quite different from what's now in GetOrganelle including the commands/scripts.

Please have your IT guys update it.

**Comment by sabrtoothcat** [comment]
Will do, thank you for your help:)
