### ISSUE TITLE
how to install get_organelle_config.py embplant_mt

### ISSUE THREAD

**Issue by sabrtoothcat** [Kinggerm/GetOrganelle#104]
Hi,

Im trying to run getorganelle but it says i haven't installed the mt database...(error message below)

From where and how do I install the embplant_mt database ?

Please help 

############################################################################
ERROR: default embplant_pt,embplant_mt database not added yet!

Install it by: get_organelle_config.py -a embplant_pt,embplant_mt
or
Install all types by: get_organelle_config.py -a all

**Comment by Kinggerm** [comment]
Just do it literally,

    get_organelle_config.py -a embplant_pt,embplant_mt

**Comment by sabrtoothcat** [comment]
I did. I typed it in the terminal and it says command not found... (see below) not sure what is wrong 

[clee@login2 getorganelle]$  get_organelle_config.py -a embplant_pt,embplant_mt
-bash: get_organelle_config.py: command not found

**Comment by sabrtoothcat** [comment]
Thank you for your quick response. 

I am currently working on a cluster called chpc where getorganelle 1.7.5 is installed.

**Comment by Kinggerm** [comment]
How did you/administrator install GetOrganelle?
Make sure the installation follows the one of the three ways from the official guide

**Comment by Kinggerm** [comment]
I will temporarily close this issue for no reply.
