### ISSUE TITLE
Error: Error: Read A00679:559:H527HDSX2:1:1216:15682:9674 1:N:0:CGGACGT+ACGTCCGG has more read characters than quality values.

### ISSUE THREAD

**Issue by qingjiaowohlj** [Kinggerm/GetOrganelle#109]
Sorry to disturb you again, I can run the test data but when I run my own data with the following errors:

Error: Error: Read A00679:559:H527HDSX2:1:1216:15682:9674 1:N:0:CGGACGT+ACGTCCGG has more read characters than quality values.
terminate called after throwing an instance of 'int'
Aborted (core dumped)
(ERR): bowtie2-align exited with value 134

2021-10-30 12:17:51,411 - ERROR: 
Traceback (most recent call last):
  File "/home/peng/anaconda3/envs/getorganelle/bin/get_organelle_from_reads.py", line 3880, in main
    random_seed=options.random_seed, verbose_log=options.verbose_log, log_handler=log_handler)
  File "/home/peng/anaconda3/envs/getorganelle/bin/get_organelle_from_reads.py", line 1110, in estimate_maximum_n_reads_using_mapping
    which_bowtie2=which_bowtie2)
  File "/home/peng/anaconda3/envs/getorganelle/lib/python3.7/site-packages/GetOrganelleLib/pipe_control_func.py", line 398, in map_with_bowtie2
    raise Exception("")
Exception

Total cost 34.70 s
Please email jianjun.jin@columbia.edu and jinjianjun@mail.kib.ac.cn if you find bugs!
Please provide me with the get_org.log.txt file!

I tried my three different data, they have the same error.Please give me some advice.

Best wishes

**Comment by qingjiaowohlj** [comment]
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7445807/get_org.log.txt)

**Comment by Kinggerm** [comment]
https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#err-bowtie2-align-died-with-signal-6-abrt-core-dumped

**Comment by Kinggerm** [comment]
I received only new issues but no feedbacks, so I have to assume assume you have no further issues with this error and close it. Keep a good habit respect the help if you need help.

**Comment by qingjiaowohlj** [comment]
Sorry, I'm very grateful to get your help, and followed your advice, but I don't know weather my data is ok.
(getorganelle) peng@peng-System-Product-Name:~/miniconda3/envs/getorganelle$ md5sum forward.fq reverse.fq.
909ebe8a64f1fa6fc303e170832a0f23  forward.fq
(getorganelle) peng@peng-System-Product-Name:~/miniconda3/envs/getorganelle$ md5sum reverse.fq
7fcba56df6f23f576307252b4aa56553  reverse.fq


Best wishes

**Comment by Kinggerm** [comment]
"use md5sum or shasum to ensure the data integrity during every data transfer process", not show it to me

Google MD5 or ask your IT assistant for it. After that, ask the sequencing company for the MD5.txt file.

**Comment by qingjiaowohlj** [comment]
Sorry, I used md5 to check the data integrity, and showed the data is OK, but it still had the same error.

**Comment by Kinggerm** [comment]
> https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#err-bowtie2-align-died-with-signal-6-abrt-core-dumped

Following the link that I've sent two weeks ago, locate the troublesome lines. See them through your eyes.

I will not reply to your further comments on the current issue of read errors.
