### ISSUE TITLE
GetOrganelle can't find dependencies

### ISSUE THREAD

**Issue by nterhoeven** [Kinggerm/GetOrganelle#11]
Hi @Kinggerm 

when running GetOrganelle, I get the following warning:

```
WARNING: bowtie2 not in the path! 
```

I get the same message for the other dependencies. However, all dependencies are in my `$PATH` and I can call them from the command line directly. 

Do you have any idea what causes this?

Best,

Niklas

**Comment by Kinggerm** [comment]
Hi Niklas,

Did you run get_organelle_reads.py in the exactly same environment with testing the dependencies? People occasionally met the same problem when they did not.
You can also attach the log file next time if the problem still exists.

Best,
Jianjun

**Comment by nterhoeven** [comment]
Hi Jianjun,

I am running this in a VM where only GetOrganelle an the dependencies are installed, so it should be the same environment. 

I re-ran it and got the same issue. Here is the log file: [get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/3148322/get_org.log.txt)

```
$ type bowtie2
bowtie2 is hashed (/home/vmadmin/software/bowtie2-2.3.5-linux-x86_64/bowtie2)
```

Best,

Niklas

**Comment by Kinggerm** [comment]
Hi Niklas,

There was someone who used 'screen' that was not correctedly configured and thus used a different env from the direct running in a shell. Before yours, that was the only "configured but still not found in the path" case reported by GetOrganelle users. So I cannot tell what your problem is at this point.
Could you somehow share the vm? I want to try to figure out.

Best,
Jianjun

**Comment by Kinggerm** [comment]
Hi Niklas,

Although I cannot figure out what is going on with your vm, in new version (GetOrganelle v1.6.0), I added dependencies to GetOrganelle's repository which could be called automatically. The installation process is much easier now.
Also I added options such as "--which-bowtie2", "--which-spades" in case users want to use their own.
Hope all these helps.

Best,
Jianjun
