### ISSUE TITLE
Mis-installation with mixed versions

### ISSUE THREAD

**Issue by qingjiaowohlj** [Kinggerm/GetOrganelle#110]
Sorry, anther error:
(getorganelle) peng@peng-System-Product-Name:~/data$ /home/peng/data/miniconda3/bin/get_organelle_from_reads.py -1 forward.fq -2 reverse.fq -R 10 -k 21,45,65,85,105 -F animal_mt -o animal_mt_out
Traceback (most recent call last):
  File "/home/peng/data/miniconda3/bin/get_organelle_from_reads.py", line 34, in <module>
    _GO_PATH = GO_PATH
NameError: name 'GO_PATH' is not defined
I download two version cause the latest version has error: “PackagesNotFoundError: The following packages are not available from current channels:

  - getorganellelib“
  -  so I download v1.6.4. Just title shows.

**Comment by Kinggerm** [comment]
You may had chaotic incomplete installations of different GetOrganelle versions. Thoroughly remove all versions you had installed, then install GetOrganelle following official guide. If your issue persists, ask a IT assistant for help first.
