### ISSUE TITLE
run on fasta contigs

### ISSUE THREAD

**Issue by biothomme** [Kinggerm/GetOrganelle#111]
Hello, I would like to run you cool tool on MAG contigs. those are already in fasta format. I tried the `get_organelle_from_reads.py -u FILE` option on GetOrganelleLib 1.7.3.3, but it does not work. 
Are there any ways you see to run getorganelle of fasta contigs?

I would feel grateful for help.

**Comment by Kinggerm** [comment]
Do you mean get_organelle_from_assembly.py?

**Comment by biothomme** [comment]
either of them, the question is more, if there is any way to use it for fasta assemblies (MAG contigs) without assembly graphs

**Comment by Kinggerm** [comment]
I'm not sure if I get you or not. I would use flye to make graph first then use get_organelle_from_assembly.py to extract the target from the graph

**Comment by biothomme** [comment]
yes sorry for the confusion. I was asking if get_organelle supports simple fasta assemblies of the chloroplast genomes ! I neither have quality data, nor a fasta graph assembly.

But I think it just does not work with my simple fasta contigs...
Thanks a lot for your answers as support!

**Comment by Kinggerm** [comment]
There is no direct support.

If the assembled fasta file is not super big (>100Mb), you may also use `reconstruct_graph_from_fasta.py` (of GetOrganelle) to generate the assembly graph, then do extraction using `get_organelle_from_assembly.py`

**Comment by biothomme** [comment]
that is brilliant :))) MERCI!
