### ISSUE TITLE
Can't get a complete chloroplast genome. The result is just a bunch of scaffolds without any connection.

### ISSUE THREAD

**Issue by bigchen98** [Kinggerm/GetOrganelle#113]
Hi there,
I'd like ask for help about a unsolvable issue during the genome assembly of chloroplast. At first, I try to run the default parameter given by the official document, the result goes not good.
get_organelle_from_reads.py -1 1_clean.fq -22_clean.fq -s ./seed.fasta  -o ./plastome_output3 -R 15 -k 21,45,65,85,105 -F embplant_pt

Then, according to the wiki help document, I change the -R -k -t paramrter, but nothing changes.
get_organelle_from_reads.py -1 1_clean.fq -22_clean.fq -s ./seed.fasta  -o ./plastome_output3 -t 16 -R 20 -k 21,35,45,55,65,75,85,95,105,115,127 -F embplant_pt

The get_org.log.txt and embplant_pt.K127.contigs.graph1.selected_graph.gfa are uploaded together. Can you take a look and provide some advice? Appreciate it! 
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7622633/get_org.log.txt)

**Comment by Kinggerm** [comment]
*gfa* was not attached. Besides,  we do not need the *.gfa* file but the *.fastg* file.

Please refer to https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#what-should-i-do-with-incomplete-resultbroken-assembly-graph carefully before further comments. You were NOT following the help document at all!
