### ISSUE TITLE
How to assemble the mitochondria of mosses

### ISSUE THREAD

**Issue by lbxxhxsy** [Kinggerm/GetOrganelle#115]
Hello!
How to assemble the moss chloroplast encountered problems
During the assembly process, there was a situation of "killed" under the chloroplast reference sequence of higher plants. After replacing the reference sequence with the Marchantia polymorpha FASTA format sequence downloaded from the NCBI, there was still a situation of "killed". In the example given on the official website, "If you want to use NC_047400 and NC_047059 as a custom seed database, you only need to download the fasta file from genbank, put them into a fasta file (for example, legume_cp.fasta), and then run GetOrganelle. There is still the previous situation.
Please solve this problem for me now, I'll be waiting anytime!

**Comment by Kinggerm** [comment]
I'm afraid that I do not have enough information to understand your problem. 

"killed" was usually triggered by your system or administrator, which has nothing to do with a reference.

**Comment by lbxxhxsy** [comment]
Do you mean that the computer hardware is not enough? If the data is 2 billion bps, what kind of computer configuration do you recommend?

**Comment by lbxxhxsy** [comment]
![Uploading Ubuntu 64 位-2021-12-16-17-41-06.png…]()

**Comment by Kinggerm** [comment]
The figure is still invalid

**Comment by Kinggerm** [comment]
> Do you mean that the computer hardware is not enough? If the data is 2 billion bps, what kind of computer configuration do you recommend?

Probably due to insufficient memory, if you are running it on your laptop. But if you are running in a cluster, you should ask your administrator.

There is no universal answer for all datasets and all organelle types. For embplant_pt, 16G will be enough for >90% datasets and 32G for >99% datasets.

**Comment by lbxxhxsy** [comment]
Thanks
