### ISSUE TITLE
Insufficient initial reads leads to SPAdes error

### ISSUE THREAD

**Issue by DW8496** [Kinggerm/GetOrganelle#117]
I'm using GetOrganelle for some samples. 
Some samples were successfully assembled, however the assembling of the others failed by SPAdes error.

get_org.log.txt showed below
2021-12-10 18:03:34,361 - ERROR: Error with running SPAdes: == Error ==  system call for: "['/home/User/bin/SPAdes-3.15.0-Linux/bin/spades-core', '/home/tendo/ngs/ABCD/mapping/trim_fastq/BG600.
Spades.log showed below
0:00:00.002     1M / 10M   ERROR   General                 "(construction.cpp          : 144)   Failed to determine read length for library #0. Check that not only merged reads are present."

Could I fix this error with some spades options or quality filtering for fastq file?
And I could not understand what "merged reads" is. Is it about a contamination?
Thanks in advance

[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7731795/get_org.log.txt)
[params.txt](https://github.com/Kinggerm/GetOrganelle/files/7731796/params.txt)
[spades.log](https://github.com/Kinggerm/GetOrganelle/files/7731797/spades.log)
.

**Comment by Kinggerm** [comment]
With your own seed, it seems there are basically no plastome reads (only 1 read, see get_org.log.txt Line 65). SPAdes will definitely fail in the case of insufficient reads.

The issue could be cause by your own seed or the dataset itself. You can try to remove "-s Lsiceraria_P.fa" to see what will happen first.

**Comment by DW8496** [comment]
I replaced the seed file with completely assembled plastid reads by GetOrganelle and this issue is solved.
Thank you so much.
