### ISSUE TITLE
Insert gaps with get_organelle_from_assembly.py - ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by zactobias44** [Kinggerm/GetOrganelle#119]
Hello again,

With this same command:

`get_organelle_from_assembly.py -g extended*Bs_mito_sc6ab.label.fastg.Ncontigs_added.fastg --genes /vortexfs1/home/ztobias/BotryllusMito/metadata/Bs_mito_sc6ab.label.fasta -t 8 -o out -F anonym --expected-min-size 1450 --expected-max-size 1550 --overwrite`

I am getting the following error in the log file right after the second attempt to disentangle as circular genome:

`ValueError: max() arg is an empty sequence`

This is preceded by a lot of traceback, which can be found in the attached log. I've also included the post slim graph. (again, with txt appended to allow for github upload)

Any help would be much appreciated!

Many thanks!
[slimmed_assembly_graph.fastg.txt](https://github.com/Kinggerm/GetOrganelle/files/7736205/slimmed_assembly_graph.fastg.txt)
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7736207/get_org.log.txt)

**Comment by Kinggerm** [comment]
Hi,

Thanks for posting this issue. This bug has been fixed in the latest 1.7.5.2, which is currently only available through github (not in bioconda).

**Comment by zactobias44** [comment]
Thanks! I'll try with a github install.
