### ISSUE TITLE
When assembled on the server using Getorganelle, the resulting file is incomplete

### ISSUE THREAD

**Issue by zhaoying888** [Kinggerm/GetOrganelle#126]
During the assembly of CP and ITS, the assembled result file was incomplete. It was normally assembled before, but this situation began to occur after the reference was added and reassembled.
![_@6NG0AGT198EPIGM1WI(TU](https://user-images.githubusercontent.com/97380840/148674758-483b86a3-e804-42bd-9e84-17afa6d153b4.png)
[CP_get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7834682/CP_get_org.log.txt)
[ITS_get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7834683/ITS_get_org.log.txt)

**Comment by Kinggerm** [comment]
`2022-01-09 14:05:54,329 - WARNING: numpy/sympy/scipy not available! Disentangling disabled!!`

Incomplete installation leads to the incomplete result.

**Comment by zhaoying888** [comment]
Roger that, problem solved, thank you!


| |
昆明植物所 赵颖
|
|
***@***.***
|
签名由网易邮箱大师定制
On 1/10/2022 01:28，Jianjun ***@***.***> wrote：

Closed #126.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
