### ISSUE TITLE
SPAdes (pre-assembly/assembly) failed issue on M1 macs

### ISSUE THREAD

**Issue by DinoRamos** [Kinggerm/GetOrganelle#127]
Hello,

I'm new to python and just installed GetOrganelle today. To see if the program was installed correctly, I ran Example 1 as instructed but the following errors came up
WARNING: Pre-assembling failed. The estimateions for embplant_pt-hitting base-coverage and word size may be misleading.
WARNING: Assembling exited halfway.

I tried running Example 2 as well and the same errors come up.

Have I done something wrong during the installation which may be affecting the results?

Thanks for the help!

[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7848522/get_org.log.txt)

**Comment by Kinggerm** [comment]
Thanks for reaching out. 

I believe it was the problem with the GetOrganelleDep version of SPAdes, which does not seem to work in your running environment. Other dependencies look quite good.

You may remove SPAdes from local GetOrganelleDep (/Users/dinoangeloramos/Applications/bin/GetOrganelle/GetOrganelleDep/macOS/SPAdes) and try to install SPAdes from its source (https://github.com/ablab/spades), or from brew or conda. Please make sure it is added to the PATH so that GetOrganelle is able to call it.

Let me know the updates.

**Comment by DinoRamos** [comment]
I installed SPAdes from the source and re-ran the Arabidopsis simulation on GetOrganelle but it resulted in the same issue. 

[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7855640/get_org.log.txt)

I checked to see if the test dataset for SPAdes 3.15.3 works and also ran into an error, apparently an [issue on M1 macs](https://github.com/ablab/spades/issues/839). The workaround suggested was to set a memory limit. I'm not sure if this is also the issue with running GetOrganelle since SPAdes is a dependency.

**Comment by Kinggerm** [comment]
Thanks for the report. Good to know it works with `-m`.

I think you are right. You can use `--spades-options` to pass additional arguments to SPAdes in GetOrganelle, e.g. `--spades-options "-m 16"`. Let me know if it works for you.

I will try to fix it from the GetOrganelle aspect.

**Comment by DinoRamos** [comment]
It looks like changing the -m of spades doesn't work either. I tried it with both the "-m 16" and "-m 1024" with the same errors as earlier.

[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7879980/get_org.log.txt)

**Comment by Kinggerm** [comment]
Could you please also provide the spades.log?
Besides, how did the spades test work with -m?

**Comment by DinoRamos** [comment]
Sure, the spades test finished with warnings. Here is the spades.log
[spades.log](https://github.com/Kinggerm/GetOrganelle/files/7890223/spades.log)

**Comment by Kinggerm** [comment]
I meant, the `spades.log` accompanied by `get_org.log.txt`, not the test one.
Thanks!

**Comment by DinoRamos** [comment]
Oh sorry, here they are. I tried changing the python version to see if it would make a difference. Running python 3.10.1 produces the error I reported earlier, but the spades.log hardly contains anything:
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7895236/get_org.log.txt)
[spades.log](https://github.com/Kinggerm/GetOrganelle/files/7895239/spades.log)
 
On the other hand, running python 3.9.9 produces more errors, but the spades.log shows that it finished assembly:
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7895288/get_org.log.txt)
[spades.log](https://github.com/Kinggerm/GetOrganelle/files/7895275/spades.log)

**Comment by Kinggerm** [comment]
Thank you so much for the results from two Python versions. It is very helpful to troubleshoot for the moment.

For the 3.9.9 one, `--spades-options` was not passed to the `Pre-assembling` resulting a non-fatal error, but passed to the final `Assembling` so that SPAdes finished and GetOrganelle generated the complete plastome. Following this, I will try to fix GetOrganelle with the `-m` option used for all spades calls on M1 macs.

For the 3.10.1 one, I have no idea. There is barely information in the spades.log. Let's keep an eye on the updates.

**Comment by Kinggerm** [comment]
I don't have a M1 to test. Could you also test 3.9.9 with a very small `-m`, e.g. `-m 0.1g`, so that we can know what may happen if the memory is insufficient? Thanks!

**Comment by DinoRamos** [comment]
I tried it with -m 0.1g and no extended_spades folder was generated in the output, although the seed folder has a spades.log file which I've attached below
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7911596/get_org.log.txt)
[spades.log](https://github.com/Kinggerm/GetOrganelle/files/7911597/spades.log)

**Comment by Kinggerm** [comment]
Thanks!

So the temporary solution for you is using `Python 3.9.9` and `GetOrganelle 1.7.5.3`:get_organelle_from_reads.py with a suitable `--spades-options` value.

**Comment by DinoRamos** [comment]
I just tried it out and it works with --spades-options "-m 1024". thanks!

**Comment by Kinggerm** [comment]
Thanks to SPAdes developers! 
Monterrey workaround introduced in (https://github.com/ablab/spades/releases/tag/v3.15.4)

**Comment by EugeniaArth** [comment]
I have macOS Monterey 12.6 and SPAdes-3.15.5-Darwin and see the same mistake but with some samples only.  And another  strange thing - when I used SPAdes within Snakemake for 40 bacterial samples it was ~50% of resulted scaffolds and contains.fasta with 5-7 kb size. When I repeat assembly in single mode the most of scaffolds increased to 1.5-2 Mb. Can somebody explain what happens? The example of log for sample with 4 kb size:
[spades.log](https://github.com/Kinggerm/GetOrganelle/files/13378496/spades.log)

**Comment by JianjunJin** [comment]
Thanks for adding more information for this thread. Sorry to know that the issue persists for you.
However, the GetOrganelle repo may not be the best place to seek for help in SPAdes.
