### ISSUE TITLE
Error with running SPAdes: == Error ==  system call for: (...) finished abnormally, OS return value: -11

### ISSUE THREAD

**Issue by Ruben9161** [Kinggerm/GetOrganelle#128]
Dear Jianjun Jin,

I ran GetOrganelle and got this error message: **Error with running SPAdes: == Error ==  system call for: (...) finished abnormally, OS return value: -11.**

I searched related issues but nothing about error value **-11**.

I would appreciate any help to fix this problem.
get_org and spades logs attached.
[spades.log](https://github.com/Kinggerm/GetOrganelle/files/7849076/spades.log)
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7849077/get_org.log.txt)

**Comment by Kinggerm** [comment]
The pinned #83 should be the right place to post, where you may find some solutions. 
Let me know the updates.

**Comment by Ruben9161** [comment]
Oh sorry, my bad.
I searched with the wrong terms.

Anyway, thanks for your help.
I will keep you updated.
