### ISSUE TITLE
Unable to install embplant_pt, and embplant_mt

### ISSUE THREAD

**Issue by Nbpgr-Nbpgr** [Kinggerm/GetOrganelle#129]
Dear Sir,
I have run the get_organelle_from_reads.py command in Ubuntu terminal, but command can not run and throw some installing error. 
This is an error
env1) user@user:~$ get_organelle_from_reads.py -1 S-alatum_R1.fastq.gz -2 S-alatum_R2.fastq.gz -o plastome_output  -F embplant_pt -R 10

############################################################################
ERROR: default embplant_pt,embplant_mt database not added yet!

Install it by: get_organelle_config.py -a embplant_pt,embplant_mt
or
Install all types by: get_organelle_config.py -a all

Please help me to install embplant_mt and embplant_pt or all
i have tried so many times but failed to install, when i try to install show one more error i.e Bowtie2 is not available, but Bowtie2 is already exist.
Therefore, i requested to solve my problem as soon as possible.
Regards,

Mukesh Kumar

**Comment by Kinggerm** [comment]
Those who complained that they had bowtie2 but still got the `Bowtie2 is not available` error usually had not really tried running it.  #85 and #102  are where you should read solutions and post follow-ups before opening this new issue.

I will close this issue unless your issue is different from available issues. In that case, please provide the following info:
1. Which GetOrganelle version
2. How you installed GetOrganelle
3. More running environment info

**Comment by Nbpgr-Nbpgr** [comment]
Sir,
As per your need related details are given below:-
1. Conda version is 4.11.0 and Python version is 3.7.11
2. My GetOrganelle version is GetOrganelle v1.7.5
3. I am install GetOrganelle through conda and running environment info is Ubuntu 18.04.6 LTS, Processor is Intel® Xeon(R) Silver 4216 CPU @ 2.10GHz × 64

**Comment by Kinggerm** [comment]
What did you get if you type in `bowtie2 --help` through terminal?

**Comment by Nbpgr-Nbpgr** [comment]
Dear Sir,
Seeking your help for failure in plant mitochondrial assembly. 

At outset, thanks very much for the tool 'GetOrganelle'.  Although we lack command in using the command line programming (CLP) tools, your tool gave us confidence that we too could make organelle assemblies in house, with minimal knowledge in CLP.  In fact, this tool has raised our benchmarks in making the successful single contig circular chloroplast assemblies in minutes to hours! 

However, while proceeding further to make the mitochondrial assemblies, we got stuck.  Attaching herewith the log file of the mitochondrial assembly that we had attempted.  It would be of great help if you could suggest us some alternative go abouts to make a successful single contig level mitochondrial assembly.

Looking forward for your help in this regard.
Regards,
Mukesh `Kumar`
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/8076827/get_org.log.txt)
