### ISSUE TITLE
slimming finishes for the larger K values but apparently gets stuck on the lower ones

### ISSUE THREAD

**Issue by Kinggerm** [Kinggerm/GetOrganelle#130]
I seem to be having the same issue, though running it via `get_organelle_from_reads.py` on an animal_mt.
      It assembles, and slimming finishes for the larger K values but apparently gets stuck on the lower ones.

_Originally posted by @travc in https://github.com/Kinggerm/GetOrganelle/issues/81#issuecomment-1011315652_

**Comment by Kinggerm** [comment]
If the larger k could deliver the complete genome, the smaller ones will not be used. Thus, slimming lower k results usually contributes minor to the final result. You can ignore slimming smaller ones by using `--ignore-k`.
Specifically, you can kill your current job and rerun the same command plus ` --continue --ignore-k 85` so that it will restart from the slimming process and ignore results from kmers < 85.

**Comment by travc** [comment]
Wow, that's a quick response.  Thanks, that does the trick.  

I know this isn't the right forum, but a very quick question...
Is adapter trimming recommended?  How about quality trimming?
I've done a bit of testing with and without and don't see an obvious difference, but don't have a known sequence to compare with either.

**Comment by Kinggerm** [comment]
> @Kinggerm Wow, that's a quick response. Thanks, that does the trick.
> 
> I know this isn't the right forum, but a very quick question... Is adapter trimming recommended? How about quality trimming? I've done a bit of testing with and without and don't see an obvious difference, but don't have a known sequence to compare with either.

Don't do miscellaneous issue. Next time, your question will be just deleted. It's easy to find the answer #78

**Comment by travc** [comment]
@Kinggerm I'll assume you aren't trying to sound like a jerk.   Next time, don't call basic usage info which appears to be missing from the paper and primary docs "easy to find".  That might be an issue worth addressing actually.

Feel free to delete this and your previous response since it is off topic.

**Comment by Kinggerm** [comment]
@travc 
Thanks for the suggestion. There are always something that we thought to be out of the scope of the tool really need our attention. Your point will definitely make contribution to improving the basic usage.

I'm sorry for your unpleasant feeling due to my unprofessional reply. I hope you can understand that there are also other things we need to do to improve the community, which includes better issue management. I will delete those off topic response and be happy to receive your new posts.
