### ISSUE TITLE
Disentangling failed: No module named scipy

### ISSUE THREAD

**Issue by SSmith-NUIG** [Kinggerm/GetOrganelle#132]
[get_org_private.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7908158/get_org_private.log.txt)
Hi, 
GetOrganelle seems unable to import scipy for the disentangling stage.

I'm running it on an anaconda environment with python 3.6.
If I run python in the terminal and type import scipy it works no problem.
If I create a testing python script which imports scipy it also works with no problems.

From the log output:
PYTHON LIBS: GetOrganelleLib 1.7.5; numpy 1.18.5; sympy 1.5.1; scipy 1.5.2

**Comment by Kinggerm** [comment]
Please ALWAYS attach the `get_org.log.txt` file if applicable

**Comment by SSmith-NUIG** [comment]
> Please ALWAYS attach the `get_org.log.txt` file if applicable

Attached it to the OP now.

**Comment by Kinggerm** [comment]
Thanks!
Could you please resume the run with "--verbose --continue" attached and post the new log file here?

**Comment by SSmith-NUIG** [comment]
> Thanks! Could you please resume the run with "--verbose --continue" attached and post the new log file here?

Will do tomorrow once I have access to the HPC again. I'll edit this post with the output

**Comment by Kinggerm** [comment]
Thanks for the feedback. 
It still seems to be a scipy importing error because no other code blocks will trigger this error.

Could you please try following command inside the python of your HPC:

    from scipy import stats, inf, log

**Comment by SSmith-NUIG** [comment]
> Thanks for the feedback. It still seems to be a scipy importing error because no other code blocks will trigger this error.
> 
> Could you please try following command inside the python of your HPC:
> 
> ```
> from scipy import stats, inf, log
> ```

Thanks, that did the trick. My environment was missing some Mkl libraries.

**Comment by Kinggerm** [comment]
Good to know.

And thanks again. I have modified the associated code blocks, reporting `from scipy import stats, inf, log` error instead of `No module named scipy`.

**Comment by o-william-white** [comment]
Just to add, I got the same error with the example data but it was fixed by downgrading scipy from 1.12 to 1.11.3.

**Comment by JianjunJin** [comment]
@o-william-white Thanks a lot! It seems that `scipy` 1.12 does not have `inf` and `log`, which can be replaced with `numpy`.

BTW, in the [next big release](https://github.com/Kinggerm/GetOrganelle/tree/intermediate_graph), GetOrganelle uses `gekko` instead of `scipy`.

**Comment by JianjunJin** [comment]
Before the formal release of `1.8.0`, I just added some fixes to `1.7.7.1`, including compatibility with `scipy 1.2`. `1.7.7.1` is now available in bioconda.

**Comment by o-william-white** [comment]
Thanks @Kinggerm
