### ISSUE TITLE
Why do chloroplast assembly of some individuals not result in direct loop formation

### ISSUE THREAD

**Issue by zhaoying888** [Kinggerm/GetOrganelle#133]
All chloroplasts assembled from the sequences tested by BDO were directly cycled, but at least half of the resequencing data tested by ANno were not directly cycled when assembled（215）. May I ask why?

**Comment by Kinggerm** [comment]
For posting an issue, please ALWAYS provide the details, e.g. log files and graphs.

For non-circular result, refer to https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#what-should-i-do-with-incomplete-resultbroken-assembly-graph first.

**Comment by zhaoying888** [comment]
> For posting an issue, please ALWAYS provide the details, e.g. log files and graphs.
> 
> For non-circular result, refer to https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#what-should-i-do-with-incomplete-resultbroken-assembly-graph first.

Thank you!
