### ISSUE TITLE
Seeking  your help for the failure in plant mitochondrial assembly -reg

### ISSUE THREAD

**Issue by Nbpgr-Nbpgr** [Kinggerm/GetOrganelle#135]
Dear Sir,

At outset, thanks very much for the tool 'GetOrganelle'.  Although we lack command in using the command line programming (CLP) tools, your tool gave us confidence that we too could make organelle assemblies in house, with minimal knowledge in CLP.  In fact, this tool has raised our benchmarks in making the successful single contig circular chloroplast assemblies in minutes to hours! 

However, while proceeding further to make the mitochondrial assemblies, we got stuck.  Attaching herewith the log file of the mitochondrial assembly that we had attempted.  It would be of great help if you could suggest us some alternative go abouts to make a successful single contig level mitochondrial assembly.

Looking forward for your help in this regard.
With thanks and regards,
Mukesh Kumar
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/8076854/get_org.log.txt)

**Comment by Kinggerm** [comment]
Please check https://github.com/Kinggerm/GetOrganelle#contact before posting issues.

A short reply to your question is that using short-read sequencing data most plant mitogenomes cannot be assembled into a single circular contig. The explanations can be found on the homepage and in our GetOrganelle paper.
