### ISSUE TITLE
Different looping path in different samples

### ISSUE THREAD

**Issue by Axolotl233** [Kinggerm/GetOrganelle#137]
Hi community,

I assembly the plastome of some sample using getorganelle, these samples are same species.  when i checked result and choosed sequence which have longest IR region as final assembly result, i found some sample have different path.

here is a simply sample :

in sample1.gfa, i get the best result which connection sequence as `1807-,37653+,1849_513_1813_31309_1119_30737_1513_1843_1861-,38119_1819_38055+,37653+,1865_1267_1675+,1471+,1865_1267_1675-,37653-,38119_1819_38055-(circular)`
the start part `1471+` of fasta have ~25000 bp

in sample2.gfa, i get the best result which connection sequence as
`134_150_27143_27121-,26881-,110+,20_27281-,26881+,122+,140+,122-,26881-,20_27281+(circular)`
 the start part `134_150_27143_27121-` of fasta have ~ 56505bp

although it not effect gene annotation, i hope to align all of plastomes for some phylogenetic analysis.

i have tried random sub-sample origin sequence of sample2 and add seed sequence of sample1 when assembled sample2, but all of these are not works. 

the results have uploaded in appendix, Could you have any advice of this?
[sample.zip](https://github.com/Kinggerm/GetOrganelle/files/8089550/sample.zip)

**Comment by Kinggerm** [comment]
Firstly, there is no single best path but a pair of best paths (see [here](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#what-are-the-differences-of-complete1path_sequencefasta-and-complete2path_sequencefasta-output-files) for more). Please check the pairs and find the concordant path across species. Just in case, I suppose you already did that.

Secondly, the counting you provided does not make sense, e.g., `1471+` is not the "start" and does not correspond to `134_150_27143_27121-`. Here I provide you with a detailed description of the paths in the following table (scroll right to view more).

| **sample** | **attributes** | **LSC** | **IR** | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**SSC**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |
|----|----|----|----|----|
| **sample1.gfa\^** | _path(s)_ | `1807-,37653+,1849_513_1813_31309_1119_30737_1513_1843_1861-` | `38119_1819_38055+,37653+,1865_1267_1675+`/ `1865_1267_1675-,37653-,38119_1819_38055-` | `1471+` |
| | _\*length_ | 81676-105\*2-105\*2=`81256 bp` | 21412-105\*2=`21202 bp` | 12876-105\*2=`12666 bp` |
| **sample2.gfa\^^** | _path(s)_ | `134_150_27143_27121-,26881-,110+` |  `20_27281-,26881+,122+`/`122-,26881-,20_27281+` | `140+` |
| | _\*length_ | 81669-105\*2-105\*2=`81249 bp` | 21413-105\*2=`21203 bp` | 12852-105\*2=`12642 bp` |

*\*lengths are calculated as the sum of contig lengths minus the overlaps (N*105 bp)

^ Visualization of sample1.gfa with IRs in red. Note that contig-37663 is a repeat shared by IR and LSC.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/8598031/154604949-4a708313-8900-4506-a290-25506ab83f70.png">

^^ Visualization of sample2.gfa with IRs in red. Note that contig-26881 is a repeat shared by IR and LSC.
<img width="994" alt="image" src="https://user-images.githubusercontent.com/8598031/154605423-d83b4345-d69f-4922-965c-8d7eb7f2de0c.png">

**Comment by Axolotl233** [comment]
thank you for quicky response. 

you are right, i choosed one fasta of pairs as best result, which SSC is positive. and I am sorry for wrote `1807`  as `1407` incorrectly in question part.

although both fasta have same start composition (LSC), they have different in start contig of LSC, like `1807-` in sample1 and `134_150_27143_27121-` in sample2. this condition make diffcult to align these sequence using mafft of muscle, could you have any solution in situation?

by the way, how to visualize gfa file with annotation like your reply, i used bandage but no length and contig name infomation in output plot.

**Comment by Kinggerm** [comment]
I see. Your concern is the direction of the LSC. You may use get_organelle_from_assembly.py with "--reverse-lsc" to extract a new result set from the *.gfa file.

Just put ticks on the left panel of Bandage. Another tip, you may also load the *.CSV file into Bandage and put a tick on the CSV data to visualize the labels that GetOrganelle generated.

**Comment by Axolotl233** [comment]
Thank you, perfectly solved~
