### ISSUE TITLE
The result of the assembly is incomplete

### ISSUE THREAD

**Issue by zhaoying888** [Kinggerm/GetOrganelle#142]
The raw data is complete, but the assembled results are incomplete

![图片](https://user-images.githubusercontent.com/97380840/155636650-6af6bfa5-b034-4947-bbd7-a55ee79e4df9.png)
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/8137722/get_org.log.txt)

**Comment by Kinggerm** [comment]
You can solve the ERROR you encountered by updating GetOrganelle, preferably to the latest version.
