### ISSUE TITLE
The assembly result is incomplete

### ISSUE THREAD

**Issue by zhaoying888** [Kinggerm/GetOrganelle#147]
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/8253983/get_org.log.txt)
The assembly result is not empty
![图片](https://user-images.githubusercontent.com/97380840/158394809-ba89973f-35ce-44e8-b46b-a4183af24244.png)

**Comment by Kinggerm** [comment]
Sorry for the delay.

The reads file is likely damaged or incomplete. 
You may add `--verbose` to the end of the GetOrganelle command to see details. Besides, you should check the data integrity using `md5`.

Let me know the updates.

**Comment by zhaoying888** [comment]
I have checked the sequence integrity of these 5 samples, and all other data were complete except for 4, but the chloroplast assembly result was still incomplete
[01get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/8343898/01get_org.log.txt)
[02get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/8343900/02get_org.log.txt)
[03get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/8343901/03get_org.log.txt)
[04get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/8343909/04get_org.log.txt)
[05get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/8343910/05get_org.log.txt)
![结果文件展示](https://user-images.githubusercontent.com/97380840/159972209-a899204f-1fae-4166-b326-2f535dae600d.png)
[CP_sh.txt](https://github.com/Kinggerm/GetOrganelle/files/8343913/CP_sh.txt)

**Comment by Kinggerm** [comment]
1.7.0c was the one with a bug and was published two years ago. Please update GetOrganelle to the latest version.

**Comment by zhaoying888** [comment]
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/8367687/get_org.log.txt)
I have used the latest version of the software, but the error is still the same, there is still no assembly result

**Comment by Kinggerm** [comment]
1. The errors are NOT the same:
    a) `ERROR: Disentangling failed: 'Vertex' object has no attribute 'conncetions'`
    b) `(ERR): bowtie2-align died with signal 9 (KILL) `

2. Check the data file integrity in case you got the `(ERR): bowtie2-align died with signal 9 (KILL) `
