### ISSUE TITLE
Integer end argument expected, got float

### ISSUE THREAD

**Issue by lurens** [Kinggerm/GetOrganelle#15]
Hello
I am testing your tool for assembly both chloroplast and mitochondrion genome
Unfortunately the process stops after spades (see get_org.log)
Any idea on how to solve the issue?
Lorenzo
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/3320435/get_org.log.txt)

**Comment by Kinggerm** [comment]
Hi Lorenzo,

Thanks for pointing out this bug. 
This associated with different returning type of math.ceil() between Python2 and Python3. 
Fixed! Please update GetOrganelle.

Cheers!
Jianjun

**Comment by lurens** [comment]
Now it works
Thanks 
Lorenzo
