### ISSUE TITLE
old version of SPAdes is unstable in some machines, needing updating

### ISSUE THREAD

**Issue by wangyuhang970520** [Kinggerm/GetOrganelle#152]
Command line: /home/j12/miniconda3/envs/py36/bin/spades.py	-t	10	--phred-offset	33	-1	/home/j12/Chloroplast/bxy/output_3/extended_1_paired.fq	-2	/home/j12/Chloroplast/bxy/output_3/extended_2_paired.fq	--s1	/home/j12/Chloroplast/bxy/output_3/extended_1_unpaired.fq	--s2	/home/j12/Chloroplast/bxy/output_3/extended_2_unpaired.fq	-k	21,105	-o	/home/j12/Chloroplast/bxy/output_3/extended_spades	

System information:
  SPAdes version: 3.13.0
  Python version: 3.6.12
  OS: Linux-4.19.0-18-amd64-x86_64-with-debian-10.11

Output dir: /home/j12/Chloroplast/bxy/output_3/extended_spades
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/j12/Chloroplast/bxy/output_3/extended_1_paired.fq']
      right reads: ['/home/j12/Chloroplast/bxy/output_3/extended_2_paired.fq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
    Library number: 2, library type: single
      left reads: not specified
      right reads: not specified
      interlaced reads: not specified
      single reads: ['/home/j12/Chloroplast/bxy/output_3/extended_1_unpaired.fq']
      merged reads: not specified
    Library number: 3, library type: single
      left reads: not specified
      right reads: not specified
      interlaced reads: not specified
      single reads: ['/home/j12/Chloroplast/bxy/output_3/extended_2_unpaired.fq']
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset: 33
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 105]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/j12/Chloroplast/bxy/output_3/extended_spades/tmp
  Threads: 10
  Memory limit (in Gb): 9

======= SPAdes pipeline started. Log can be found here: /home/j12/Chloroplast/bxy/output_3/extended_spades/spades.log

===== Read error correction started. 

== Running read error correction tool: /home/j12/miniconda3/envs/py36/share/spades-3.13.0-0/bin/spades-hammer /home/j12/Chloroplast/bxy/output_3/extended_spades/corrected/configs/config.info

The program was terminated by segmentation fault
=== Stack Trace ===

**_== Error ==  system call for: "['/home/j12/miniconda3/envs/py36/share/spades-3.13.0-0/bin/spades-hammer', '/home/j12/Chloroplast/bxy/output_3/extended_spades/corrected/configs/config.info']" finished abnormally, err code: -11

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory._**

**Comment by Kinggerm** [comment]
Sorry for the long delay.
I just updated the SPAdes binaries to 3.15.4, under [GetOrganelleDep 1.7.0](https://github.com/Kinggerm/GetOrganelleDep/releases/tag/v1.7.0), which may help the [installation without conda](https://github.com/Kinggerm/GetOrganelle/wiki/Installation#option-2-using-the-setuppy) community.
