### ISSUE TITLE
ERROR: BLAST Database error: Error: Not a valid version 4 database

### ISSUE THREAD

**Issue by zhongyan5058** [Kinggerm/GetOrganelle#174]
ERROR: BLAST Database error: Error: Not a valid version 4 database

**Comment by Kinggerm** [comment]
Probably due to a fatal error in default database installation. Please use the following command to remove installed databases.

    get_organelle_config.py --clean

then reinstall the type(s) you need, such as

    get_organelle_config.py -a embplant_pt,embplant_mt
