### ISSUE TITLE
Getting multiple "Disentangling Failed" even after changing settings. 

### ISSUE THREAD

**Issue by giorge-costa** [Kinggerm/GetOrganelle#182]
Dear Dr. Jin

I am very new to the bioinformatics field, and have recently started using GetOrganelle for my research project. I have been trying to assemble an animal mitochondrial genome, but am currently facing the "Disentangling Failed" problem, even after trying to change the settings as appointed in the FAQ. Could you please give me a hint to what I'm doing wrong? 

I have run GetOrganelle three times, and got these outputs: 

First try:

[1_get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/9264227/1_get_org.log.txt)

![1](https://user-images.githubusercontent.com/110634581/182975480-bc7ea518-ed2d-46be-b88d-de50de89f6e0.png)

Second try:

[2_get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/9264229/2_get_org.log.txt)

![2](https://user-images.githubusercontent.com/110634581/182975524-eeaa88c3-fd78-4803-ad59-5a184f8221d7.png)

Third try: 

[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/9264230/get_org.log.txt)

![3](https://user-images.githubusercontent.com/110634581/182975904-ff7e196b-17c1-453a-b384-5bf713415375.png)

Thank you so much in advance.

Best regards,
Giorge

**Comment by JianjunJin** [comment]
According to the graph, the second and third tries generated [organelle-complete graph](https://github.com/Kinggerm/GetOrganelle/wiki/Terminology), which is improved from the first try.

However, there are too many repeats within this graph, making it unsolvable with short-read data. So, there is no way to get a complete mitogenome from current data, while the contigs are still usable for phylogenetic analysis.

**Comment by zhengyanstu** [comment]
I have met a similar problem and generated a more complicated graph. Too many short reads made it hard to separate different mitochondrial DNA loops. Could you give me suggestions to solve this problem?

**Comment by Kinggerm** [comment]
> I have met a similar problem and generated a more complicated graph. Too many short reads made it hard to separate different mitochondrial DNA loops. Could you give me suggestions to solve this problem?

As I mentioned, there is no way to get a complete mitogenome from short reads. You may use long reads or the current incomplete result, depending on your research purpose.

**Comment by zhengyanstu** [comment]
Thanks a million
