### ISSUE TITLE
Cannot download repodata: Solving environment: failed with initial frozen solve. Retrying with flexible solve

### ISSUE THREAD

**Issue by dheerajdhotre** [Kinggerm/GetOrganelle#183]
While trying to install GetOrganelle using conda, I am getting following error
My network is working fine. I am trying to install it on ubuntu server 20.04
I have updated conda with **conda update conda**
Please suggest

**Comment by dheerajdhotre** [comment]
This is the command I have used. It has taken more than 30 mins and it still shows "Solving environment"
$conda install -c bioconda getorganelle
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment:

**Comment by JianjunJin** [comment]
I will create a virtual environment for getorganelle with 
    
    conda create -n getorganelle
    conda activate getorganelle

then check if you can install it smoothly,
    
    conda install -c bioconda getorganelle

if not, check the solutions here https://stackoverflow.com/questions/63734508/stuck-at-solving-environment-on-anaconda, among which `conda config --set channel_priority strict` worked for me once.

**Comment by dbenner63** [comment]
hello, i tried all above solutions, none that worked. Please help.

**Comment by JianjunJin** [comment]
> hello, i tried all above solutions, none that worked. Please help.

Please try to install GetOrganelle using the second approach: https://github.com/Kinggerm/GetOrganelle/wiki/Installation#option-2-using-the-setuppy

**Comment by dbenner63** [comment]
> > hello, i tried all above solutions, none that worked. Please help.
> 
> @dbenner63 Please try to install GetOrganelle using the second approach: https://github.com/Kinggerm/GetOrganelle/wiki/Installation#option-2-using-the-setuppy

Hey @JianjunJin this isn’t for Getorganelle this is for Compás Wood. It’s not letting me create the environment based on the repo data provided as per my original post.

**Comment by JianjunJin** [comment]
> > > hello, i tried all above solutions, none that worked. Please help.
> > 
> > 
> > @dbenner63 Please try to install GetOrganelle using the second approach: https://github.com/Kinggerm/GetOrganelle/wiki/Installation#option-2-using-the-setuppy
> 
> Hey @JianjunJin this isn’t for Getorganelle this is for Compás Wood. It’s not letting me create the environment based on the repo data provided as per my original post.

Please leave your msg at [Compás Wood](https://github.com/petrasvestartas/compas_wood), not here. Thanks!

**Comment by dbenner63** [comment]
Just for clarification, isn't the repodata for json a Conda issue? or is it a Compas Wood issue?
