### ISSUE TITLE
Issue -F anonym

### ISSUE THREAD

**Issue by sihellem** [Kinggerm/GetOrganelle#19]
Hi @Kinggerm,

I wanted to try to assemble the bacterium Wolbachia from paired Illumina reads. So I used the option -F anonym (even though I don't know if it would work considering the size of expected genome; 1Mb); and I get the following error:

> GetOrganelle v1.6.2
> 
> get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
> Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.
> 
> Python 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]
> Python libs: numpy 1.17.0; sympy 1.4; scipy 1.3.0
> Dependencies: Bowtie2 2.3.5.1; SPAdes 3.13.0; Blast 2.2.30
> /home/ulb/ebe/dfournie/miniconda3/bin/get_organelle_from_reads.py -1 213-Cavi-1_S1_R1_paired.fastq -2 213-Cavi-1_S1_R2_paired.fastq -o Wolbachia_S1_output -s wCle_genome.fasta --genes wCle_features.fasta -R 3 -k 21,45,65,85,105 -F anonym
> 
> 2019-07-31 20:25:08,651 - INFO: Setting '--target-genome-size [3983366]' for estimating the word size value for anonym type.
> 2019-07-31 20:25:08,694 - INFO: Setting '--expected-max-size [19916830]' for estimating the word size value for anonym type.
> 2019-07-31 20:25:08,955 - INFO: Pre-reading fastq ...
> 2019-07-31 20:25:08,955 - INFO: Estimating reads to use ...
> 2019-07-31 20:25:10,930 - ERROR: 
> Traceback (most recent call last):
>   File "/home/users/d/f/dfournie/miniconda3/lib/python3.7/site-packages/GetOrganelle-1.6.2-py3.7.egg/EGG-INFO/scripts/get_organelle_from_reads.py", line 3541, in main
>     random_seed=options.random_seed, verbose_log=options.verbose_log, log_handler=log_handler)
>   File "/home/users/d/f/dfournie/miniconda3/lib/python3.7/site-packages/GetOrganelle-1.6.2-py3.7.egg/EGG-INFO/scripts/get_organelle_from_reads.py", line 915, in estimate_maximum_n_reads_using_mapping
>     / max_organelle_base_percent * GUESSING_FQ_SEQ_INFLATE_TO_FILE
> KeyError: 'anonym'

Is it something to be done here?

Thanks in advance,
Simon

**Comment by Kinggerm** [comment]
Hi Simon,

Sorry for the inconvenience of a new bug induced by this version. I just fixed it. Please update GetOrganelle to the latest version (v1.6.2d).
Few people used '-F anonym' and fewer use GetOrganelle to assemble bacteria. Currently I only tested GetOrganelle in a range of plant/animal/fungi samples. I even don't know whether it would works fine for bacteria or not. Please let me know the updates.
Also, thanks for letting me know this issue! Please let me know if there is any other questions/issues.

Best,
Jianjun

**Comment by sihellem** [comment]
Dear Jianjun,

Thank you for your reply. I reinstalled the soft, and tried again but I get the same error.

Maybe I do not use the right installation link? See below:

> curl -L https://github.com/Kinggerm/GetOrganelle/releases/download/v1.6.2/v1.6.2-linux.tar.gz | tar zx
> cd GetOrganelle/
> python setup.py install

Thank you in advance,
Simon

**Comment by Kinggerm** [comment]
Are you running multiple runs at the same time in the same place? This error seems abnormal.
Have you checked that `Wolbachia_S1_output/2-213-Cavi-1_S1_R2_paired.fastq` was generated or not?
PS: I am doing fieldwork these days but I would try to reply in time. 

Thanks for the feedback again!
Jianjun

**Comment by sihellem** [comment]
The file did not generate indeed. Only one job was running, but it seems we reached our disk quota. We will launch it on a smaller dataset, and will let you know in case something comes up.

Thanks again,
Simon
