### ISSUE TITLE
Error during spades assembly

### ISSUE THREAD

**Issue by toddmclay** [Kinggerm/GetOrganelle#2]
Hello,

I have been trying to run GetOrganelle and am running into an error in the Spades assembly - 

'2018-04-13 14:11:36,749 - ERROR: Error in SPAdes: 
== Error ==  system call for: "[\'/apps/spades/3.11.1/bin/spades\', \'/flush1/mcl300/Alangium/GetOrganelle/Alangium_output4/filtered_spades/K95/configs/config.info\']" finished abnormally, err code: -8\n\n
2018-04-13 14:11:36,749 - ERROR: Assembling failed.

This error occurs in the final kmer assembly, no matter how many kmer values I try. For example, if I set kmer = 75,85,95, it will fail at 95. If I set k = 75, 85, it will fail at 85. If I set k=75, it won't run at all. 

Here is the code I am using to run the software: 

```
python /home/mcl300/GetOrganelle/get_organelle_reads.py \
-1 /home/mcl300/Alangium/13_4T_R1.fastq -2 /home/mcl300/Alangium/13_4T_R2.fastq \
-s /home/mcl300/Alangium/MG524996.fasta -w 103 -o Alangium_output4 \
-R 10 -F -k 75,85,95 -P 0 --out-per-round --no-remove-duplicates --verbose --spades-options "--memory 1000 --threads 10 --phred-offset 33"
```
Any help would be appreciated. 

Cheers,
Todd

**Comment by Kinggerm** [comment]
Hi Todd,

Can you post the complete log files of GetOrganelle and SPAdes here or send them to my email?

Cheers,
Jianjun

**Comment by toddmclay** [comment]
Hi Jianjun,

Thanks for your response. I've attached the log files for both GetOrganelle and Spades. 

Cheers,
Todd


[GetOrganelle.15134537.txt](https://github.com/Kinggerm/GetOrganelle/files/1913490/GetOrganelle.15134537.txt)
[spades.log](https://github.com/Kinggerm/GetOrganelle/files/1913491/spades.log)

**Comment by toddmclay** [comment]
Hi Jianjun,

I wonder if 'error code: -8' is a default linux error code? I will try it on another computer and see if it completes. I have run several other softwares which include spades and have not run into any errors.

Thanks for your suggestions,,
Todd

**Comment by Kinggerm** [comment]
Hi Todd,

Have you went through it?

Best,
Jianjun
