### ISSUE TITLE
Is "embplant_pt Seed Database v0.0.0" compatible with "embplant_pt Label Database v0.0.1"?

### ISSUE THREAD

**Issue by ForestCat1** [Kinggerm/GetOrganelle#217]
Dear @Kinggerm 
I couldn't initialize the database because the connection to github kept failing (neither of the following codes worked)
`get_organelle_config.py --add embplant_pt,embplant_mt`
or
`curl -L https://github.com/Kinggerm/GetOrganelleDB/releases/download/0.0.1/v0.0.1.tar.gz | tar zx`

So I manually downloaded "v0.0.1.tar.gz" from [the link given above](https://github.com/Kinggerm/GetOrganelleDB/releases/download/0.0.1/v0.0.1.tar.gz) 

Then I extracted the files by running `tar -zxvf v0.0.1.tar.gz` and got the following screen output
```
0.0.1/
0.0.1/.DS_Store
0.0.1/SeedDatabase/
0.0.1/SeedDatabase/embplant_nr.fasta
0.0.1/SeedDatabase/embplant_pt.fasta
0.0.1/SeedDatabase/animal_mt.fasta
0.0.1/SeedDatabase/fungus_mt.fasta
0.0.1/SeedDatabase/embplant_mt.fasta
0.0.1/SeedDatabase/other_pt.fasta
0.0.1/SeedDatabase/fungus_nr.fasta
0.0.1/LabelDatabase/
0.0.1/LabelDatabase/embplant_nr.fasta
0.0.1/LabelDatabase/embplant_pt.fasta
0.0.1/LabelDatabase/animal_mt.fasta
0.0.1/LabelDatabase/fungus_mt.fasta
0.0.1/LabelDatabase/embplant_mt.fasta
0.0.1/LabelDatabase/other_pt.fasta
0.0.1/LabelDatabase/fungus_nr.fasta
```

Finally, I successfully initialized the database by running `get_organelle_config.py -a embplant_pt,embplant_mt --use-local ./0.0.1`

When I list the databases I have added, I find the version of "embplant_pt Seed Database" is different from that of "embplant_pt Label Database", here is the screen output after I run `get_organelle_config.py --list`
```
embplant_pt Seed Database:	0.0.0	e8e5f461d6e5fe67c5314e46c61265e6ff1079886af3b959609dde2be97d870d
embplant_mt Seed Database:	0.0.1.minima	2f28612e7c2280a7273738eded0dd2fcfb59c6153c1cf3bac15e4e7ed1bf4e89
embplant_pt Label Database:	0.0.1	cca977f68f5764bdd9e4b82e711adcfc12d752e78f088cea05c8283dea74fa7e
embplant_mt Label Database:	0.0.1	f3621444441fbf4fa98835999b20e7ac1673a8866cb119707200412c46263570
```

**Is "embplant_pt Seed Database v0.0.0" compatible with "embplant_pt Label Database v0.0.1"?**
Why the version of "embplant_pt Seed Database" in above screen output of gunzip is 0.0.1 but what I actually added is v0.0.0?

Many thanks!

**Comment by Kinggerm** [comment]
Thanks for reaching out with great details about the issue!

In short, you are good. You can go ahead using GetOrganelle with no worries.

Here are some details. I know the version control here looks a little confusing. Yes, the embplant_pt seed database remains unchanged while the entire database version changes. `get_organelle_config.py` detects the version by hash value -  I believe I made some changes to a local branch of GetOrganelle so that it recognized the latest - but maybe it was never pushed. But, anyway, it will affect nothing.
Meanwhile, the embplant_mt minima issue was a bug in version detection fixed in the latest GitHub version of GetOrganelle. Nevertheless, the bug itself will not affect using GetOrganelle once you have the database initialized.

**Comment by ForestCat1** [comment]
> Thanks for reaching out with great details about the issue!
> 
> In short, you are good. You can go ahead using GetOrganelle with no worries.
> 
> Here are some details. I know the version control here looks a little confusing. Yes, the embplant_pt seed database remains unchanged while the entire database version changes. `get_organelle_config.py` detects the version by hash value - I believe I made some changes to a local branch of GetOrganelle so that it recognized the latest - but maybe it was never pushed. But, anyway, it will affect nothing. Meanwhile, the embplant_mt minima issue was a bug in version detection fixed in the latest GitHub version of GetOrganelle. Nevertheless, the bug itself will not affect using GetOrganelle once you have the database initialized.



Thank you for providing me the details about database version!  Indeed, I have got the complete plastome with GetOrganelle from my sequencing data.
