### ISSUE TITLE
Differences of complete*.1.path_* and complete*.2.path_* output files

### ISSUE THREAD

**Issue by KeleyKeley** [Kinggerm/GetOrganelle#22]
I could get final files *.complete.graph1.1.path_sequence and *.complete.graph1.2.paht_sequence fasta files at the end.

I want to know the differences between these output files.
I think the bases are the same (maybe almost the same??).

Thank you.

**Comment by Kinggerm** [comment]
I believe you would also have 
`WARNING: More than one circular genome structure produced ...`
`WARNING: Please check the final result to confirm whether they are simply flip-flop configurations!` 
in the log file.

In most cases, you would get the same assembly graph like this, 
![embplant_pt K127 complete graph1 selected_graph](https://user-images.githubusercontent.com/8598031/66938755-5c7bca80-f074-11e9-9f88-7cf414fa16de.png)
meaning that complete*.1.path_* and complete*.2.path_*  are flip-flop configurations mediated by IR ([Walker et al. 2015](https://bsapubs.onlinelibrary.wiley.com/doi/full/10.3732/ajb.1500299)). A intuitive feeling is that they have an "inversion" in the SSC.

Both of them are right and coexist in plant. For publication, people tend to use just one of them. You can pick the configuration of which the SSC region is in the same direction with most of your data or outgroup, which makes downstream annotation/analysis easier (https://github.com/Kinggerm/GetOrganelle/issues/5#issuecomment-470766453).

Let me know if you have further questions!
