### ISSUE TITLE
Feature request: memory flag for spades

### ISSUE THREAD

**Issue by SethMusker** [Kinggerm/GetOrganelle#222]
Hi,

I've discovered an oddity about spades, which is that it often crashes while saying it's run out of RAM, but in fact there is plenty of RAM available. Strangely, if you specify something ridiculous like  `--memory 1024`, it runs fine. I've been running into this error when using GetOrganelle (using various version including v. 3.15.4 compiled from source, and binaries from 3.15.5 and 3.15.3). 

See [<jemalloc>: Error in malloc(): out of memory](https://github.com/ablab/spades/issues/494#top)

Would you be willing to add a `--memory` flag to `get_organelle_from_reads.py` to pass to spades?

Thanks,
Seth

**Comment by Kinggerm** [comment]
Hi Seth, 

Thanks for reporting this with the solution. I will think about adding `--spades-memory` to `get_organelle_from_reads.py`. 
Before then, you may use the `--spades-options` flag of `get_organelle_from_reads.py`to fulfill it, e.g. 

    get_organelle_from_reads.py --spades-options "--memory 1024" [other options]

Best,
J

**Comment by SethMusker** [comment]
Hi Jianjun,

Ah, for some reason I hadn't twigged to that option. Good to know. Thanks for your quick response!

S
