### ISSUE TITLE
Error with running SPAdes: The program was terminated by segmentation fault

### ISSUE THREAD

**Issue by SowmyaPulapet** [Kinggerm/GetOrganelle#231]
Hi,
  I using GetOrganelle for the first time. I followed the method using setup.py to install GetOganelle. The dependencies are from GetOrganelleDep. My data has approximate size of ~9 gb. The command I am using is : 

`/Tools/GetOrganelle/get_organelle_from_reads.py -1 data_1.fq.gz -2 data_2.fq.gz -o data_output -R 15 -F embplant_pt -t 10`

I am getting the following error: 

> ERROR: Error with running SPAdes: The program was terminated by segmentation fault
> ERROR: Assembling failed.

The log file has been attached here. Hope someone would help me. 

Thank you. 
[log.txt](https://github.com/Kinggerm/GetOrganelle/files/10479948/log.txt)

**Comment by JianjunJin** [comment]
It should be similar to many of the previous issues, e.g. #226 

So, what is the outcome of `spades.py --test` coming from the SPAdes of GetOrganelleDep?

**Comment by SowmyaPulapet** [comment]
I got this error while running `spades.py --test` : 

> == Error ==  system call for: "['/Tools/GetOrganelle/GetOrganelleDep/linux/SPAdes/bin/spades-hammer', '/Tools/GetOrganelle/GetOrganelleDep/linux/SPAdes/bin/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -11

Here's the complete log [spades.log](https://github.com/Kinggerm/GetOrganelle/files/10486268/spades.log)

**Comment by JianjunJin** [comment]
It seems the version at GetOrganelleDep is not working in your environment.
Is it possible for you to install SPAdes from other approaches, like from the SPAdes website or GitHub? 
After you install SPAdes by your own and add spades bin to the $PATH, you should remove the entire directory of `/Tools/GetOrganelle/GetOrganelleDep/linux/SPAdes/`, thus GetOrganelle can automatically detect the new SPAdes.

Please let me know you updates.

**Comment by SowmyaPulapet** [comment]
I removed `/Tools/GetOrganelle/GetOrganelleDep/linux/SPAdes/` as you said. I didn't have to install spades again, had previusly installed one. Now the assembly is finished. 

Thank you ! @JianjunJin
