### ISSUE TITLE
Using embplant_mt and embplant_pt not possible

### ISSUE THREAD

**Issue by marcelglueck** [Kinggerm/GetOrganelle#263]
Dear Jianjun,

thank you for providing and maintaining GetOrganelle.

I am currently facing strange issues when trying to use embplant_mt and/or embplant_pt. I am currently running GetOrganelle 1.7.7.0 in an Apptainer and use job arrays to assemble genomes from different species in parallel. All relevant information (including the GetOrganelle database to use for the species) is parsed through the following text file. 
Col 1: species, Col2: database, Col3: name of output subdirectory
```
Arep	animal_mt	Arep_mt
Bs	embplant_mt	Bs_mt
Bs	embplant_pt	Bs_pt
Colp	animal_mt	Colp_mt
Cs	embplant_mt	Cs_mt
Cs	embplant_pt	Cs_pt
Cyl	animal_mt	Cyl_mt
Drob	animal_mt	Drob_mt
Edep	animal_mt	Edep_mt
Hyro	animal_mt	Hyro_mt
Ida	animal_mt	Ida_mt
Lafl	animal_mt	Lafl_mt
Mali	animal_mt	Mali_mt
Peal	animal_mt	Peal_mt
```

The three databases animal_mt, embplant_pt and embplant_mt were obtained through the get_organelle_config.py script and are stored in a folder (one subdirectory for each of the databases). I double-checked that building the databases is error-free. The get_organelle_from_reads.py gets its information from the text file to select the database to use. Interestingly, assembling genomes with this script works fine in species that use the animal_mt database. However, species that use the embplant_pt or embplant_mt databases (Cs and Bs) fail with the message 

```
ERROR: default embplant_pt,embplant_mt database not added yet!

Install it by: get_organelle_config.py -a embplant_pt,embplant_mt
or
Install all types by: get_organelle_config.py -a all
```
I have the impression that GetOrganelle wants to force me to use the combined databases. However, I would really prefer, running the assemblies for mt and pt separately. 
Because only runs that use the embplant_pt or embplant_mt databases fail, it seems highly unlikely that a dependency is causing this issue.

Many thanks in advance.

**Comment by JianjunJin** [comment]
You are correct that, by default, GetOrganelle forces users to use the combined database of embplant_pt and embplant_mt, even if you assemble one type of them, for biological considerations. You can bypass this restriction, which is NOT recommended, by using `-s` and `--genes` to specify the fasta files of the seed and label database, e.g. `-s ~/.GetOrganelle/SeedDatabase/embplant_pt.fasta --genes ~/.GetOrganelle/LabelDatabase/embplant_pt.fasta`.

What I recommend is to follow the default approach. As soon as your Apptainer can access shared data, you may configure the database path for each singularity following [here](https://github.com/Kinggerm/GetOrganelle/wiki/Initialization#default-directory), either `--config-dir` and `GETORG_PATH` should work.

**Comment by marcelglueck** [comment]
Thanks for the clarification. I got it to work. 
Thank you and all the best,
Marcel
