### ISSUE TITLE
Broken assembly graph

### ISSUE THREAD

**Issue by nsmt89** [Kinggerm/GetOrganelle#28]
Hi, 
I tried to use my one seed/reference genome but I cant seem to keep it on running. I have copied my *.fasta file in SeedDatabase folder and change the command line for embplant_pt. Also my assembly produced 11 contigs in the file embplant_pt.K105.contigs.graph1.1.path_sequence.fasta. I am very new and using Bandage is quite confusing to me. Do you have any suggestions for me to complete and circularized my assembly? 
Thank you for your time.

**Comment by Kinggerm** [comment]
With such little information, I can't understand what you really did for assembly. Please attach a log file of your run.

**Comment by nsmt89** [comment]
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/4084438/get_org.log.txt)

I am so sorry, here is my log file

**Comment by Kinggerm** [comment]
Thank you for the log file.
It seems that you have a plenty of data. There are lots of ways to improve the successful rate. You can try two ways below first:
1. Decrease the `word size`, which is currently automatically estimated as 112. You can try `-w 101` or smaller, while the smaller `word size` is, the more computational resources will be used.
2. Set `--reduce-reads-for-coverage inf` to use all the data. If you do it, please decrease the rounds to `-R 10`.

If you post the picture of the assembly graph visualized using Bandage, it could better help to identify the problem.

**Comment by nsmt89** [comment]
![graph](https://user-images.githubusercontent.com/5387645/72701983-2296f480-3b8c-11ea-924a-e6f10194fc6e.jpg)
 Currently trying to troubleshoot according to your suggestions. Attached is my Bandage image from previous run. Is it possible for me to get circularized genome assembly?

**Comment by Kinggerm** [comment]
"Is it possible for me to get circularized genome assembly?"
Re: It's really hard to say. It varies upon data.

From this graph, I don't see significant assembly graph disentangling puzzles. It's simply broken graph. Let's wait to see the new results.

**Comment by nsmt89** [comment]
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/4085022/get_org.log.txt)
![graph](https://user-images.githubusercontent.com/5387645/72708320-6c3c0b00-3b9d-11ea-9cd9-5ad90f06e815.jpg)
Hi, attached are latest graph and log files. The graph looked like broken graph as well. Do you have any suggestions on troubleshooting this?

**Comment by Kinggerm** [comment]
I'm sorry it's barely improved. It could be the problem during the library preparation or sample DNA quality. As I see it, there's little hope of complete.
You may try a smaller word size, more k-mer gradients, `-M 1`, `-J 1`, etc. But I believe, at last, you need a reference to adding gaps between contigs manual or use `join_spades_fastg_by_blast.py`. You should manually clean the assembly graph before using `join_spades_fastg_by_blast.py`.

**Comment by nsmt89** [comment]
Thank you for your response. Can I use my own fasta file which only contain one complete chloroplast genome as seed? To put in -F embplant_pt? By manually clean the assembly graph you mean using bandage?

**Comment by nsmt89** [comment]
Another question, I tried assembled my genome using MITObim (based on related reference genome) and it produces one fasta file with 'logical' sequence length (~170k bp). I tried to annotate the assembly but there are few genes that does not seem to be annotated correctly and the orientation of inverted repeat seems weird. Is there any chance that I can use GetOrganelle to modify the assembly data? Or use data from GetOrganelle to re-assemble using MITObim? I really appreciate if you can help. I have been troubleshooting the problem for almost two years while finishing my other research objectives.

**Comment by Kinggerm** [comment]
> Thank you for your response. Can I use my own fasta file which only contain one complete chloroplast genome as seed? To put in -F embplant_pt? By manually clean the assembly graph you mean using bandage?

You can use your own fasta file as seed by simple use '-s your_cp_genome.fasta'. Don't change `-F embplant_pt` nor the default seed database.. # Before running GetOrganelle, you are strongly suggested to use `get_organelle_from_reads.py -h` or `get_organelle_from_reads.py --help` for all options and their illustrations (current version of manual).

We recommend using bandage to clean the graph manually.

**Comment by Kinggerm** [comment]
> Another question, I tried assembled my genome using MITObim (based on related reference genome) and it produces one fasta file with 'logical' sequence length (~170k bp). I tried to annotate the assembly but there are few genes that does not seem to be annotated correctly and the orientation of inverted repeat seems weird. Is there any chance that I can use GetOrganelle to modify the assembly data? Or use data from GetOrganelle to re-assemble using MITObim? I really appreciate if you can help. I have been troubleshooting the problem for almost two years while finishing my other research objectives.

You may try either approaches you proposed. However, GetOrganelle cannot modify a previous assembly, instead, it can take the previous result as the seed and then conduct a _de novo_ assembly. 
In addition, you may also use `--max-extending-len` to limit the extending length of GetOrganelle. For example, if it's just a small gap you want to fill, you can set this value to be very small.
Hope it helps.

**Comment by nsmt89** [comment]
Thank you for your reply. I tried to assemble using my own seed and it turn out there are lesser contigs than before (before was 11, now only 9). Is that means the result is better?
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/4095399/get_org.log.txt)
![graph](https://user-images.githubusercontent.com/5387645/72868266-78020b80-3d1c-11ea-947d-1c98a9bbe86e.png)

**Comment by Kinggerm** [comment]
Yeah, a little improvement. 

As I see from the log file, the AI and AW have not increased a lot, which means there's a plenty room of word size to be decreased. You can try `-w 89` or even smaller if your server works.
 
Besides, you may also try fast-plast, which was tested to be able to be complement to GetOrganelle according to Freudenthal et al. (https://www.biorxiv.org/content/10.1101/665869v1.full)

**Comment by nsmt89** [comment]
I really appreciate your time on helping me. I will do as your suggestions. I tried GetOrganelle after reading the paper that you suggested. Great software. Thank you again.

**Comment by Kinggerm** [comment]
Sorry for the late reply. 
GetOrganelle has the built-in limit. But I think the true limit lies on your computational resource limits.

**Comment by sarahgetachew** [comment]
Hi, attached are latest graph and log files. The graph looked like broken graph as well. Do you have any suggestions on troubleshooting this?
![Spiradiclis](https://user-images.githubusercontent.com/66486775/89040104-11c3fa00-d2f8-11ea-90a0-a022de119eec.PNG)
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/5007272/get_org.log.txt)

**Comment by Kinggerm** [comment]
I think you could try with a smaller word size, e.g. 75 or even smaller.

BTW, I don't get enough info from the graph. Please draw it in single strand and turn on the coverage. It would be better if you could load the csv file.

**Comment by sarahgetachew** [comment]
This is the graph result
![ema](https://user-images.githubusercontent.com/66486775/89042322-92d0c080-d2fb-11ea-93f9-ff4a20f27f40.PNG)
