### ISSUE TITLE
Set Startingpoint of Cicular Mitochondrial Genome

### ISSUE THREAD

**Issue by max-baer** [Kinggerm/GetOrganelle#283]
Hello Kinggerm,

I am reconstructing multiple mitochondrial genomes and have the issue, that the starting point is set quite randomly. Is there any options to set startingpoints in the software?

I added to pictures which where visualized with mitoZ to illustrate the issue. Ideally the startingpoint of both would be at the COX1 gene for example.

Best,
Max

![GFB-7667_HWNGYDSX5_3_TRICHURIS898Tiagba_S237_L003_mito_circos](https://github.com/Kinggerm/GetOrganelle/assets/124160560/4c7f5e44-2241-4319-8115-2e34c7206c32)
![GFB-7721_HWNGYDSX5_3_TRICHURIS972Tiagba_S291_L003_mito_circos](https://github.com/Kinggerm/GetOrganelle/assets/124160560/d3090e69-90f5-4c72-afba-a55c56312c3e)

**First check**
- [x] I used the GitHub search to find a similar issue or discussion and didn't find it.
- [x] I searched [GetOrganelle.wiki](https://github.com/Kinggerm/GetOrganelle/wiki) context, especially the [FAQ](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ) and browsed the [examples](https://github.com/Kinggerm/GetOrganelle/wiki/Examples) to confirm it is unexpected to happen.
- [ ] I have updated GetOrganelle to the latest released version [![GitHub release](https://img.shields.io/github/release/Kinggerm/GetOrganelle.svg)](https://GitHub.com/Kinggerm/GetOrganelle/releases/)

Please ask questions in the [Question in GitHub Discussions](https://github.com/Kinggerm/GetOrganelle/discussions/categories/q-a) unless it is a feature request or bug report.

**Comment by max-baer** [comment]
Did it manually :)

**Comment by JianjunJin** [comment]
Thanks for reaching out! 
Sorry that there is no such feature yet, which requires good annotation.
Will keep an eye on a simple solution for that.
