### ISSUE TITLE
conda install error: conda version 23.5.0 too high

### ISSUE THREAD

**Issue by sanvva** [Kinggerm/GetOrganelle#284]
**Describe the bug**

> ResolvePackageNotFound: 
>   - conda==23.3.1

**To Reproduce**
`conda  install -c bioconda getorganelle`

**Additional context**
conda 23.5.0

**Comment by JianjunJin** [comment]
Thanks for reporting this issue. 

I am not surprised that conda ran into different issues from time to time, at least for me. However, I cannot reproduce the same bug on MacOS 12.1 or Linux g275 4.18.0-193.el8.x86_64.
However, when I create a new environment with conda==23.5.0, they both get the same (similar) error

```
  - feature:/osx-64::__unix==0=0
  - feature:|@/osx-64::__unix==0=0
  - getorganelle -> sympy[version='>=1.4'] -> __unix
 ```
or

```
  - feature:/linux-64::__unix==0=0
  - feature:|@/linux-64::__unix==0=0
  - getorganelle -> sympy[version='>=1.4'] -> __unix
```

There is no up-version limit from GetOrganelle itself (see https://github.com/bioconda/bioconda-recipes/blob/master/recipes/getorganelle/meta.yaml). However, it is possible that its dependencies (like `sympy` here) are not compatible with the newer conda version, which is also weird.

My conda==23.1.0 & mamba==1.4.1 works for the installation, though. Sorry for switching the title back and forth. I'm still not sure where the real trouble is.
