### ISSUE TITLE
Issue with mitochondrial genome assembly

### ISSUE THREAD

**Issue by natcan** [Kinggerm/GetOrganelle#29]
Hi @Kinggerm ,
I was trying to assembly the mitochondrial genome (plant) with this configuration:

> GetOrganelle v1.6.2
> Python 2.7.6 (default, Nov 13 2018, 12:45:42)  [GCC 4.8.4]
> Python libs: numpy 1.14.5; sympy 1.4; scipy 1.1.0
> Dependencies: Bowtie2 2.3.5.1; SPAdes 3.13.0; Blast 2.2.30

This is the code:

`.../install/bin/GetOrganelle/get_organelle_from_reads.py -1 P9104_1_sample_10G.fastq -2 P9104_2_sample_10G.fastq -o CP9104_mit_3 -R 50 -k 21,45,65,85,105 -P 100000 -F embplant_mt`

However, I get this error:

> 2020-02-10 14:00:04,906 - INFO: Pre-reading fastq ...
> 2020-02-10 14:00:04,906 - INFO: Estimating reads to use ...
> 2020-02-10 14:00:05,657 - INFO: Tasting 100000+100000 reads ...
> 2020-02-10 14:00:12,638 - ERROR:
> Traceback (most recent call last):
>   File "/home/oscarperez/install/bin/GetOrganelle/get_organelle_from_reads.py", line 3541, in main
>     random_seed=options.random_seed, verbose_log=options.verbose_log, log_handler=log_handler)
>   File "/home/oscarperez/install/bin/GetOrganelle/get_organelle_from_reads.py", line 997, in estimate_maximum_n_reads_using_mapping
>     log_handler=log_handler if verbose_log else None, verbose_log=verbose_log)
>   File "/home/oscarperez/install/bin/GetOrganelle/get_organelle_from_reads.py", line 1227, in pre_assembly_mapped_reads_for_base_cov
>     theses_words, original_fq_files, word_size=gathering_word_size, output=more_fq_file)
>   File "/home/oscarperez/install/bin/GetOrganelle/get_organelle_from_reads.py", line 1127, in extend_with_constant_words
>     seq_line = fq_f_input_handler.readline()
> ValueError: Mixing iteration and read methods would lose data
> 
> Total cost 7.96 s

I'm not sure what the problem could be. I have successfully assembled the chloroplast genome from the same data set (45G).

Thanks in advance!

**Comment by Kinggerm** [comment]
1.6.2 has a bug in running Python 2.*.

You can use python3. But you are more recommended to update GetOrganelle to the latest stable version 1.6.2e (see here for instructions: https://github.com/Kinggerm/GetOrganelle#updating-getorganelle).

Let me know if you have further questions!

**Comment by natcan** [comment]
Yes!! I needed to update to the latest version. Running OK now :)
Thanks a lot for your prompt reply!
