### ISSUE TITLE
empty filtered paired 

### ISSUE THREAD

**Issue by Alicia-Talavera** [Kinggerm/GetOrganelle#291]
Hi, 

I have successfully used getOrganelle in the past without any issues, however, I am currently trying to assembly some plastid genomes for another project and I get the following warnings:

WARNING about Min Quality Score: Min quality score 'B'(66:2) in your fastq file is under the usual lower boundary (67, 105)
WARNING about No Paired Reads: No paired reads found?! 

In addition to these warnings, I´ve noticed that the files 'filtered_1_paired.fq' and 'filtered_2_paired.fq' are turning out to be empty, and I am not achieving circular genomes for most of the samples.  

Please find attached get_org.log file: [get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/12315741/get_org.log.txt)

My question is as follows:  

Could you please inform me why the filtered_1_paired.fq and  filtered_2_paired.fq are empty?  or could you please give me some advice regarding this issue? 

The fasta files look like this: 

@FCC70R7ACXX:5:1101:1238:2188#/1
TCAAGCTAAAGCAGGAGAAGAGAGTGAGCTTTCTGCTGAGTGAGCCCGAAGAGGAGCGGACGCACACTAGATCAGAGCAAGTTTAGCTGGCCCAATGGCA
+
___`c`ccggggaegdcg]egffhfgfd^dfhd`eaf]^cIYYcaedfgaa[bbccaadcdaYWZ\aX^bb]RSYYY`bX^R]``__b[[[^^acb_YW^
@FCC70R7ACXX:5:1101:1135:2218#/1
GATCAATATTCAGATTCATAAATCCGAGGAATCATGATTTGATCTCCTCATCTCGGTAAAATAAATCTGAAATGGAACTTCTTCTTTTTTATTCATACTT
+
^[Vcccecagecca^ceagffhfffhdgf_fghhhhhhfgb^Xacf`^fX^eaedfaf`bedfgffZ\_Z\HHV\^`^aaced_bU_bba^bbb`cdbb_
@FCC70R7ACXX:5:1101:1152:2230#/1
ATGGCTATTAGACATTTTTCCTCAAGTTCATCTAAGCAAACCAAATATATATTTTCATATATTTTGCTACTAAATACTATGTGTTCATCATAAAAAATAT

Thank you so much, 

Best wishes

 

**First check**
- [x] I used the GitHub search to find a similar issue or discussion and didn't find it.
- [x] I searched [GetOrganelle.wiki](https://github.com/Kinggerm/GetOrganelle/wiki) context, especially the [FAQ](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ) and browsed the [examples](https://github.com/Kinggerm/GetOrganelle/wiki/Examples) to confirm it is unexpected to happen.
- [ ] I have updated GetOrganelle to the latest released version [![GitHub release](https://img.shields.io/github/release/Kinggerm/GetOrganelle.svg)](https://GitHub.com/Kinggerm/GetOrganelle/releases/)

Please ask questions in the [Question in GitHub Discussions](https://github.com/Kinggerm/GetOrganelle/discussions/categories/q-a) unless it is a feature request or bug report.

**Comment by JianjunJin** [comment]
Please update GetOrganelle to the latest release and try again.

For the incomplete issue, please refer to https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#what-should-i-do-with-incomplete-resultbroken-assembly-graph

**Comment by JianjunJin** [comment]
Due to no reply, I will close this issue for now. Feel free to update the information and reopen it.
