### ISSUE TITLE
dogged request of help with Invalid version spec: =2.7

### ISSUE THREAD

**Issue by Jorge-82** [Kinggerm/GetOrganelle#296]
Hi
I am very sorry to re-post over an issue that has been already posted, but it looks like still there is no clear solution to the problem. It is about the the problems during installation of GetOrganelle.
I have tried all possible solutions offered (updating python, checking if all necessary packages are installed, conda, anaconda, you name it) and in the end I still get the depressive message:

Solving environment: failed
InvalidVersionSpecError: Invalid version spec: =2.7

Any comment would be great, thank you and sorry again

**Comment by JianjunJin** [comment]
Yeah, the conda issue can be annoying because different environments may require different solutions. Alternatives will be using Option 2 & 3 (https://github.com/Kinggerm/GetOrganelle/wiki/Installation).

But if conda is the most possible option, `Invalid version spec: =2.7` seems to be a version restriction not related to GetOrganelle config but something in your environment, have you tried creating a new conda environment, e.g. 

    conda create -n getorganelle_env python  # or update your conda to the latest version using conda update conda -n base -y
    conda activate getorganelle_env
    conda install -c bioconda getorganelle

**Comment by JianjunJin** [comment]
Also, please provide a link to the original issues that you believe to be re-posted, which helps both the maintainer and others who see your post.

**Comment by Jorge-82** [comment]
Hi. This is the situation. Thanks for any comment.

(getorganelle) jorge@jorgePC:~/anaconda3/envs$ conda install -c bioconda getorganelle
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 23.9.0

Please update conda by running
    $ conda update -n base -c defaults conda
# All requested packages already installed.

(getorganelle) jorge@jorgePC:~/anaconda3/envs$ conda update -n base -c defaults conda
Solving environment: failed

InvalidVersionSpecError: Invalid version spec: =2.7

(getorganelle) jorge@jorgePC:~/anaconda3/envs$

**Comment by Jorge-82** [comment]
(getorganelle) jorge@jorgePC:~/anaconda3/envs$ conda install -c bioconda getorganelle
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 23.9.0

Please update conda by running

    $ conda update -n base -c defaults conda



All requested packages already installed.

(getorganelle) jorge@jorgePC:~/anaconda3/envs$ conda update -n base -c defaults conda
Solving environment: failed

InvalidVersionSpecError: Invalid version spec: =2.7

(getorganelle) jorge@jorgePC:~/anaconda3/envs$

**Comment by Jorge-82** [comment]
Hi. This is the situation. Thanks for any suggestion.

(getorganelle) jorge@jorgePC:~/anaconda3/envs$ conda install -c bioconda getorganelle
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 23.9.0

Please update conda by running

    $ conda update -n base -c defaults conda



 All requested packages already installed.

(getorganelle) jorge@jorgePC:~/anaconda3/envs$ conda update -n base -c defaults conda
Solving environment: failed

InvalidVersionSpecError: Invalid version spec: =2.7

(getorganelle) jorge@jorgePC:~/anaconda3/envs$

**Comment by JianjunJin** [comment]
It seems that you have `All requested packages already installed`. 
Let me know what do you get by typing in with the `getorganelle` environment activated,

    get_organelle_from_reads.py -h

**Comment by Jorge-82** [comment]
Hi JianjunJin
I think it is working now.. 
thank you

#PC:~$ conda activate getorganelle
#(getorganelle) jorge@jorgePC:~$ get_organelle_from_reads.py -h
usage: 
Embryophyta plant plastome, 2*(1G raw data, 150 bp) reads
get_organelle_from_reads.py -1 sample_1.fq -2 sample_2.fq -s cp_seed.fasta -o plastome_output  -R 15 -k 21,45,65,85,105 -F embplant_pt
Embryophyta plant mitogenome
get_organelle_from_reads.py -1 sample_1.fq -2 sample_2.fq -s mt_seed.fasta -o mitogenome_output  -R 30 -k 21,45,65,85,105 -F embplant_mt

GetOrganelle v1.7.7.0 get_organelle_from_reads.py assembles organelle genomes from genome skimming data. Find updates in https://github.com/Kinggerm/GetOrganelle and see
README.md for more information.

optional arguments:
  -1 FQ_FILE_1          Input file with forward paired-end reads (*.fq/.gz/.tar.gz).
  -2 FQ_FILE_2          Input file with reverse paired-end reads (*.fq/.gz/.tar.gz).
  -u UNPAIRED_FQ_FILES  Input file(s) with unpaired (single-end) reads.
  -o OUTPUT_BASE        Output directory.
  -s SEED_FILE          Input fasta format file as initial seed. Default: /home/jorge/.GetOrganelle/SeedDatabase/*.fasta
  -w WORD_SIZE          Word size (W) for extension. Default: auto-estimated
  -R MAX_ROUNDS         Maximum extension rounds (suggested: >=2). Default: 15 (embplant_pt)
  -F ORGANELLE_TYPE     Target organelle genome type(s):
                        embplant_pt/other_pt/embplant_mt/embplant_nr/animal_mt/fungus_mt/fungus_nr/anonym/embplant_pt,embplant_mt/other_pt,embplant_mt,fungus_mt
  --max-reads MAX_READS
                        Maximum number of reads to be used per file. Default: 1.5E7 (-F embplant_pt/embplant_nr/fungus_mt/fungus_nr); 7.5E7 (-F
                        embplant_mt/other_pt/anonym); 3E8 (-F animal_mt)
  --fast FAST_STRATEGY  ="-R 10 -t 4 -J 5 -M 7 --max-n-words 3E7 --larger-auto-ws --disentangle-time-limit 360"
  -k SPADES_KMER        SPAdes kmer settings. Default: 21,55,85,115
  -t THREADS            Maximum threads to use. Default: 1
  -P PRE_GROUPED        Pre-grouping value. Default: 200000
  -v, --version         show program's version number and exit
  -h                    print brief introduction for frequently-used options.
  --help                print verbose introduction for all options.

(getorganelle) jorge@jorgePC:~$
