### ISSUE TITLE
How to jugde circular?

### ISSUE THREAD

**Issue by deyuanyang** [Kinggerm/GetOrganelle#302]
Hi Jin,

I would like to ask you a question: how do you determine whether the contig(s) is circular in your software?

祝好
deyuan

**Comment by JianjunJin** [comment]
If you are asking about the interpretation of the result concerning when GetOrganelle is generating a circular genome,
please browse the examples ([Example-4](https://github.com/Kinggerm/GetOrganelle/wiki/Example-4) and [Example-1](https://github.com/Kinggerm/GetOrganelle/wiki/Example-1))

There will be an INFO-line like 

    TIMESTAMP- INFO: Result status of GENOMETYPE: circular genome
