### ISSUE TITLE
How can I choose the assembled sequences

### ISSUE THREAD

**Issue by lychen83** [Kinggerm/GetOrganelle#31]
Hi Jianjun,

I have used GetOrganelle to assemble the cp genome.  Reads were generated by sequencing genomic DNA with Hiseq2500 (150bp paired reads).
After running the GetOrganelle, I got two fasta files for each sample. For example file name and sequence heads:
1-1_embplant_pt.K105.complete.graph1.1.path_sequence.fasta:
>32639050_32105184_32124232-,32481135-,32384871-,32481135+(circular)

1-1_embplant_pt.K105.complete.graph1.2.path_sequence.fasta:
>32639050_32105184_32124232-,32481135-,32384871+,32481135+(circular)
However, the two sequences are very different in some regions.  The rest seems to be completely identical.  
Which sequence should be used for further analysis?   Which is more accurate?
Thank you so much.

Best,
Lingyun

**Comment by Kinggerm** [comment]
Hi Lingyun,

In short, they are both correct. Please find a detailed answer here #22 

Best,
Jianjun

**Comment by lychen83** [comment]
Thank Jianjun. 

I have more than 10 samples, which are from different populations of the same species. 
After aligning the assembled cp sequences with several cp genomes (from the same genus and same species) downloaded from GENBANK, I found that about 70 percent of sites for our assembled cp genomes are different from that of the downloaded genomes.   What may cause the problem?  
Is it possible to use the a cp genome I downloaded from Genbank as a reference during the assembling?

Thank you so much.

Best,

Lingyun

**Comment by Kinggerm** [comment]
It's all about directions. You can prove this by conducting online blast with you sample and there will definitely be higher similarities.
Plastome is characterized as circular DNA genome, which means you can reverse it or restart it at any place. GetOrganelle may be restarting your sequence in a different direction from the online reference, which may be not convenient for downstream analysis.
Currently, you can use get_organelle_from_assembly.py to extract new paths from your `1-1_embplant_pt.K105.complete.graph1.1.selected_graph.gfa` with the `--reverse-lsc` option, such as:
> get_organelle_from_assembly.py -F plant_pt --no-slim --reverse-lsc -g 1-1_embplant_pt.K105.complete.graph1.1.selected_graph.gfa -o output

Hopefully you will get new results in the `output` folder with the same direction as the online one(s) that you are interested in.

**Comment by Yedomon** [comment]
Hello Jian-Jun Jin,
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/5600501/get_org.log.txt)
![graph_sample](https://user-images.githubusercontent.com/45568831/100309573-8d0b9300-2fee-11eb-9735-ab7982141282.png)

I successfully ran getorganelle and get a nice assembly graph. However, the node's length size is different from the assembly itself `Total:LSC:SSC:Repeat(bp) = 153338:85180:17874:25142
[sample_filtered_K85.assembly_graph.fastg.extend-embplant_pt-embplant_mt.zip](https://github.com/Kinggerm/GetOrganelle/files/5600504/sample_filtered_K85.assembly_graph.fastg.extend-embplant_pt-embplant_mt.zip)

.` Is common for this type of result? What should I do?

Please find attached my get_log.txt, fastg file and the assembly graph from Bandage.

Thank you.

**Comment by Kinggerm** [comment]
It's just about the format. The single copy node in the fastg file contains the extra overlaps (kmer*2=85*2=170 bp) of two ends.

You can check the examples here: https://github.com/Kinggerm/GetOrganelle/wiki/Example-1

**Comment by Yedomon** [comment]
Thanks a lot Jian-Jun Jin for this helpfull clarification.
