### ISSUE TITLE
Please fix SPAdes citation

### ISSUE THREAD

**Issue by asl** [Kinggerm/GetOrganelle#310]
Hello

Will you please fix the suggested SPAdes citation? E.g. https://github.com/ablab/spades/blob/spades_3.15.5/README.md#sec5 explicitly asks to cite  Prjibelski et al, 2020 (https://currentprotocols.onlinelibrary.wiley.com/doi/abs/10.1002/cpbi.102)

Thanks!

**Comment by JianjunJin** [comment]
Dear Dr Korobeynikov,

I'm very sorry for the oversight regarding the old-dated SPAdes citation, and thank you for bringing this to my attention. 
I have updated the citation as suggested. 

Your contribution to the community through SPAdes is immensely valued.

Best regards,
JianJun

**Comment by asl** [comment]
Awesome, thanks!
