### ISSUE TITLE
ERROR ON UNZIPPING THE .gz file

### ISSUE THREAD

**Issue by karthickbrlab** [Kinggerm/GetOrganelle#314]
python get_organelle_from_reads.py -1 Sample1.R1.fastq.gz -2 Sample1.R2.fastq.gz -o plastome_output -R 30 -k 21,45,65,85,105  -F embplant_pt --memory-save --reduce-reads-for-coverage inf --max-reads inf

GetOrganelle v1.7.7.0

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.7.16 (default, Jan 17 2023, 22:20:44)  [GCC 11.2.0]
PLATFORM: Linux ubuntu-desktop 6.5.0-17-generic #17~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan 16 14:32:32 UTC 2 x86_64 x86_64
PYTHON LIBS: GetOrganelleLib 1.7.7.0; numpy 1.21.6; sympy 1.7.1; scipy 1.7.3
DEPENDENCIES: Bowtie2 2.3.5.1; SPAdes 3.13.0; Blast 2.5.0
GETORG_PATH=/home/ubuntu/.GetOrganelle
SEED  DB: embplant_pt 0.0.1; embplant_mt 0.0.1
LABEL DB: embplant_pt 0.0.1; embplant_mt 0.0.1
WORKING DIR: /home/ubuntu/GetOrganelle
get_organelle_from_reads.py -1 Sample1.R1.fastq.gz -2 Sample1.R2.fastq.gz -o plastome_output -R 30 -k 21,45,65,85,105 -F embplant_pt --memory-save --reduce-reads-for-coverage inf --max-reads inf

2024-02-23 10:54:02,065 - INFO: Pre-reading fastq ...
2024-02-23 10:54:02,066 - INFO: Unzipping reads file: Sample1.R1.fastq.gz (2211446784 bytes)
2024-02-23 10:54:02,127 - ERROR: 
Traceback (most recent call last):
  File "get_organelle_from_reads.py", line 3915, in main
    raise ValueError("Empty file " + target_fq)
ValueError: Empty file plastome_output/1-Sample1.R1.fastq.gz.fastq

Total cost 7.50 s

##############################
For trouble-shooting, please 
Firstly, check https://github.com/Kinggerm/GetOrganelle/wiki/FAQ
Secondly, check if there are open/closed issues related at https://github.com/Kinggerm/GetOrganelle/issues
If your problem was still not solved, 
  please open an issue at https://github.com/Kinggerm/GetOrganelle/issues
  please provide the get_org.log.txt and the assembly_graph.fastg.*.fastg file(s) (can be visualized as *.png to protect your data privacy) if possible!

**Comment by JianjunJin** [comment]
Have you managed to manually gunzip the same file?

**Comment by JianjunJin** [comment]
It is likely to be a corruption of the input gz file or a disk writing issue.

**Comment by karthickbrlab** [comment]
Sorry..Seems like a erroneous file..couldnt unzip it as such.
