### ISSUE TITLE
TypeError: execute_blast() got an unexpected keyword argument 'percent_identity'

### ISSUE THREAD

**Issue by YLee115** [Kinggerm/GetOrganelle#327]
**First check**
- [O] I used the GitHub search to find a similar issue and didn't find it.
- [O] I searched [GetOrganelle.wiki](https://github.com/Kinggerm/GetOrganelle/wiki) context, especially the [FAQ](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ) and browsed the [examples](https://github.com/Kinggerm/GetOrganelle/wiki/Examples) to confirm it is unexpected to happen.
- [O] I have updated GetOrganelle to the latest version [![GitHub release](https://img.shields.io/github/release/Kinggerm/GetOrganelle.svg)](https://GitHub.com/Kinggerm/GetOrganelle/releases/)

**Describe the bug**

**To Reproduce**
- [O] COMMAND
- [O] <b>complete</b> `get_org.log.txt` file (required in most cases) and/or other log files
- [O] GetOrganelle version if `get_org.log.txt` does not exist

**Additional context**

------------------------------------------------------------------------------
Hi, Dr. Jin, 

I got some problems in using this program. 

I installed getorganelle version 1.7.7.1, and here is the log. 

COMMAND: 
get_organelle_from_reads.py -1 Arabidopsis_simulated.1.fq.gz -2 Arabidopsis_simulated.2.fq.gz -t 1 -o Arabidopsis_simulated.plastome -F embplant_pt -R 10 --verbose --overwrite

ERROR MESSAGE:
2024-04-18 19:47:46,630 - ERROR: 
execute_blast() got an unexpected keyword argument 'percent_identity'
2024-04-18 19:47:46,630 - ERROR: Slimming file 1/1: /media/yong/Research/11_PGL/01_greenalgae/Arabidopsis_simulated.plastome/seed/embplant_pt.initial.fq.spades/assembly_graph.fastg failed!

2024-04-18 19:47:46,630 - ERROR: 
Traceback (most recent call last):
  File "/home/yong/miniconda3/lib/python3.12/site-packages/GetOrganelle-1.7.7.1-py3.12.egg/EGG-INFO/scripts/slim_graph.py", line 1070, in main
    raise e
  File "/home/yong/miniconda3/lib/python3.12/site-packages/GetOrganelle-1.7.7.1-py3.12.egg/EGG-INFO/scripts/slim_graph.py", line 1016, in main
    in_names = blast_and_call_names(fasta_file=blast_fas, index_files=include_indices,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yong/miniconda3/lib/python3.12/site-packages/GetOrganelle-1.7.7.1-py3.12.egg/EGG-INFO/scripts/slim_graph.py", line 499, in blast_and_call_names
    execute_blast(query=fasta_file, blast_db=index_f, output=out_file, threads=threads,
TypeError: execute_blast() got an unexpected keyword argument 'percent_identity'

LOG FILES:
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/15023815/get_org.log.txt)
[slim.log.txt](https://github.com/Kinggerm/GetOrganelle/files/15023816/slim.log.txt)

I tried the latest version of blast (2.15.0, downloaded from ncbi) and older version (2.12.0, installed using "sudo apt install ncbi-blast+"), and I got the same results. 

Previously, I used version 1.7.5 and there was no error in blast. 
Please help me. 

I am always grateful for this amazing program. 

Thank you!

**Comment by JianjunJin** [comment]
This issue is likely to be caused by mixed `GetOrganelle` versions installed in your running environment where the older `GetOrganelleLib` version (with the `execute_blast ` function) is not installed using conda (e.g. `pip` or in situ) and has a higher priority to be imported when executing the script from the newer version.

Please remove the older versions or remove all versions installed, then reinstall GetOrganelle. Let me know your updates.

**Comment by YLee115** [comment]
Sorry for late response. 
I removed the older versions and reinstalled 1.7.7.1. 
Everything is OK! 

Thanks!
