### ISSUE TITLE
what doesn mean by -p? 

### ISSUE THREAD

**Issue by bioramg** [Kinggerm/GetOrganelle#33]
Hi,
I would like to know what does -p 1000000 stands for in the command? and Kmer value is important in the commands??

get_organelle_from_reads.py -1 sample_1.fq -2 sample_2.fq -o mitochondria_output -R 50 -k 21,45,65,85,105 -P 1000000 -F embplant_mt

**Comment by Kinggerm** [comment]
Please find the verbose introduction for all options using `get_organelle_from_reads.py --help` (not `-h`). I believe it will explain your `-P` question. Let me know if it doesn't.

_kmer_ value is important for improving the success rate. But if you already achieve complete organelle genome(s), different _kmer_ values generally produce a consistent result.

If you want to know more about the underlying algorithm, please read our GetOrganelle paper.

**Comment by bioramg** [comment]
Ok thank you. I will follow that...

**Comment by Kinggerm** [comment]
I'm closing this issue. Feel free to reopen it if you have further questions.
