### ISSUE TITLE
Abnormal assembly size due to incorrectly including shallow-coverage mt contig(s) in the embplant_pt selected_graph

### ISSUE THREAD

**Issue by woshi0655** [Kinggerm/GetOrganelle#338]
![graph](https://github.com/Kinggerm/GetOrganelle/assets/29584533/31bf4611-4442-433e-9652-9d43f2fd717a)
Hi, here is graph of a gfa file, base one this file I got four path_sequence.fasta files with size 184 kb, is it possible? How can I explain these results? I also used novoplasty to assemble the chloroplast genome using the same data, but only got two 144 kb chroloplast genome. 
I also upload a zip file contain all the results I got.
[13#.zip](https://github.com/user-attachments/files/15951620/13.zip)

**Comment by JianjunJin** [comment]
@woshi0655 
Hi, thanks for reaching out and sending the files over. I apologize for the delay.

This is an issue with the previous contig modeling and filtering. The 28x contig should be excluded. The true cp should be 144114 bp. 
The latest GetOrganelle (v1.8) can treat it correctly (see results attached). However, GetOrganelle 1.8 is still not released in conda yet. So should you want to use it, you may execute following

```
 mamba create -n getorganelle2 python
 mamba activate getorganelle2
 mamba install -c bioconda blast
 pip install gekko
 git clone --depth 1 --branch intermediate_graph https://github.com/Kinggerm/GetOrganelle
 pip install ./GetOrganelle
```
