### ISSUE TITLE
How to use the scipt "summary_get_organelle_output.py?

### ISSUE THREAD

**Issue by XuenaXie** [Kinggerm/GetOrganelle#39]
I would like to asked how to use the script of  "summary_get_organelle_output.py . I don't know the input file. In addition, I would like to asked what was the meaning of "Aligned: 375.33±66.39 (375.33±66.39)" , the one of  data value come from the script: evaluate_assembly_using_mapping.py.Thank you very much!

**Comment by Kinggerm** [comment]
The input of "summary_get_organelle_output.py" is the output folder(s), (after the flag "-o" in your "get_organelle_from_reads.py" command). e.g. you have multiple samples finished with

    get_organelle_from_reads.py -1 sample1_1.fq.gz -2 sample1_2.fq.gz -t 1 -o sample1-plastome -F embplant_pt -R 10
    get_organelle_from_reads.py -1 sample2_1.fq.gz -2 sample2_2.fq.gz -t 1 -o sample2-plastome -F embplant_pt -R 10
    get_organelle_from_reads.py -1 sample3_1.fq.gz -2 sample3_2.fq.gz -t 1 -o sample3-plastome -F embplant_pt -R 10

Then, you can summarize those results with

    summary_get_organelle_output.py  sample_1-plastome sample_2-plastome sample_3-plastome -o plastome_run_stat.tab

or 

    summary_get_organelle_output.py sample*-plastome -o plastome_run_stat.tab

**Comment by Kinggerm** [comment]
Thanks for posting this! I just realize that I forgot to update the description/termination for "evaluate_assembly_using_mapping.py". It's outdated and inaccurate.
It **should be "Matched: 375.33±66.39 (375.33±66.39)"**, not "Aligned: 375.33±66.39 (375.33±66.39)", meaning the mean and standard deviation of matched bases of the mapping alignment. Now I have correct the description in the code.

Refer to **Reads mapping to evaluate plastome assemblies** in the manuscript (https://www.biorxiv.org/content/10.1101/256479v4.full). The biorxiv version was actually updated again with minor clarification in our submission version to the journal, but the idea is the same.

**Comment by XuenaXie** [comment]
Thank you very much. I can successfully run the script:summary_get_organelle_output.py. Thank you for your explanation of the Matched: 375.33±66.39 (375.33±66.39).
