### ISSUE TITLE
Error correction and assembling warnings

### ISSUE THREAD

**Issue by mozhiqiong** [Kinggerm/GetOrganelle#4]
I tried to assemble chloroplast using:
get_organelle_reads.py -1 SRR6175507_1.fastq -2 SRR6175507_2.fastq -s Ref.fasta -o SRR6175507 -R 40 -k 75,85,95,105 --spades-options --careful
I got some warnings at the assembly step and I don't know whether these will obtain a  wrong assembly results or not. Below some warnings of the file spades.log:

======= SPAdes pipeline finished WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:01:08.830   316M / 3G    WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
 * 0:01:32.553   312M / 3G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 12
 * 0:01:32.555   312M / 3G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 12
 * 0:00:56.624   320M / 3G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 3
 * 0:00:56.626   320M / 3G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 3
 * 0:00:51.189   328M / 3G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 63
 * 0:01:36.512   448M / 3G    WARN    General                 (simplification.cpp        : 479)   The determined erroneous connection coverage threshold may be determined improperly

I have seet you the intact log file.

Besides, I have some single-end data to assemble, but I don't know how to deal with it using this pipeline. Can you tell me something about it?

thanks for your help.

**Comment by Kinggerm** [comment]
I understand that in this version, the introduction is kind of mess and options are sometimes not easy to find.
In the coming version (under testing, not online yet), options would be better organized. Also the introduction would be different between "-h" and "--help", with the former returning a simpler and briefer introduction, and the latter returning a complete and verbose introduction to usage.

Best,
Jianjun
