### ISSUE TITLE
Failure in slimming fastg

### ISSUE THREAD

**Issue by ZexuanZhao** [Kinggerm/GetOrganelle#42]
Operating System: macOS Catalina V10.15.6
Codes:
> get_organelle_from_reads.py -1 W2M.2_R1_trimmed.fastq.gz -2 W2M.2_R2_trimmed.fastq.gz -F animal_mt -o raw_mtgenome -t 4 -s ../F1_mt_sequences.fasta

Here is the get_org.log.txt

> GetOrganelle v1.7.0
> 
> 
> get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
> Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.
> 
> Python 3.7.7 (default, May  6 2020, 04:59:01)  [Clang 4.0.1 (tags/RELEASE_401/final)]
> PYTHON LIBS: GetOrganelleLib 1.7.0; numpy 1.18.5; sympy 1.6.1; scipy 1.5.0
> DEPENDENCIES: Bowtie2 2.3.5.1; SPAdes 3.12.0; Blast 2.6.0
> LABEL DB: animal_mt 0.0.0
> WORKING DIR: /Users/zzx/Documents/wasps/F1(F.obtusifolia,W2M.2)
> /Users/zzx/anaconda3/envs/bioconda/bin/get_organelle_from_reads.py -1 W2M.2_R1_trimmed.fastq.gz -2 W2M.2_R2_trimmed.fastq.gz -F animal_mt -o raw_mtgenome -t 4 -s ../F1_mt_sequences.fasta
> 
> 2020-07-21 17:00:47,161 - INFO: Pre-reading fastq ...
> 2020-07-21 17:00:47,161 - INFO: Estimating reads to use ... (to use all reads, set '--reduce-reads-for-coverage inf')
> 2020-07-21 17:00:47,277 - INFO: Tasting 100000+100000 reads ...
> 2020-07-21 17:00:53,140 - INFO: Estimating reads to use finished.
> 2020-07-21 17:00:53,140 - INFO: Unzipping reads file: W2M.2_R1_trimmed.fastq.gz (3801285450 bytes)
> 2020-07-21 17:01:15,974 - INFO: Unzipping reads file: W2M.2_R2_trimmed.fastq.gz (4141147876 bytes)
> 2020-07-21 17:01:39,293 - INFO: Counting read qualities ...
> 2020-07-21 17:01:39,428 - INFO: Identified quality encoding format = Illumina 1.8+
> 2020-07-21 17:01:39,429 - INFO: Trimming bases with qualities (0.00%): 33..33  !
> 2020-07-21 17:01:39,488 - INFO: Mean error rate = 0.0043
> 2020-07-21 17:01:39,489 - INFO: Counting read lengths ...
> 2020-07-21 17:02:27,611 - INFO: Mean = 145.7 bp, maximum = 151 bp.
> 2020-07-21 17:02:27,612 - INFO: Reads used = 19983821+20016206
> 2020-07-21 17:02:27,612 - INFO: Pre-reading fastq finished.
> 
> 2020-07-21 17:02:27,612 - INFO: Making seed reads ...
> 2020-07-21 17:02:27,617 - INFO: Making seed - bowtie2 index ...
> 2020-07-21 17:02:27,757 - INFO: Making seed - bowtie2 index finished.
> 2020-07-21 17:02:27,757 - INFO: Mapping reads to seed bowtie2 index ...
> 2020-07-21 17:05:55,457 - INFO: Mapping finished.
> 2020-07-21 17:05:55,458 - INFO: Seed reads made: raw_mtgenome/seed/animal_mt.initial.fq (1024219 bytes)
> 2020-07-21 17:05:55,458 - INFO: Making seed reads finished.
> 
> 2020-07-21 17:05:55,458 - INFO: Checking seed reads and parameters ...
> 2020-07-21 17:05:55,458 - INFO: The automatically-estimated parameter(s) do not ensure the best choice(s).
> 2020-07-21 17:05:55,458 - INFO: If the result graph is not a circular organelle genome, 
> 2020-07-21 17:05:55,458 - INFO:   you could adjust the value(s) of '-w'/'-R' for another new run.
> 2020-07-21 17:05:55,795 - INFO: Pre-assembling mapped reads ...
> 2020-07-21 17:11:58,405 - WARNING: Pre-assembling failed. The estimations for animal_mt-hitting base-coverage and word size may be misleading.
> 2020-07-21 17:11:58,408 - INFO: Estimated animal_mt-hitting base-coverage = 585.01
> 2020-07-21 17:11:58,548 - INFO: Reads reduced to = 17079896+17107575
> 2020-07-21 17:11:58,548 - INFO: Adjusting expected animal_mt base coverage to 500.00
> 2020-07-21 17:11:58,549 - INFO: Estimated word size(s): 116
> 2020-07-21 17:11:58,549 - INFO: Setting '-w 116'
> 2020-07-21 17:11:58,549 - INFO: Setting '--max-extending-len inf'
> 2020-07-21 17:11:58,552 - INFO: Checking seed reads and parameters finished.
> 
> 2020-07-21 17:11:58,552 - INFO: Making read index ...
> 2020-07-21 17:13:39,355 - INFO: For raw_mtgenome/1-W2M.2_R1_trimmed.fastq.gz.fastq, only top 17079896 reads are used in downstream analysis.
> 2020-07-21 17:15:27,384 - INFO: For raw_mtgenome/2-W2M.2_R2_trimmed.fastq.gz.fastq, only top 17107575 reads are used in downstream analysis.
> 2020-07-21 17:15:50,125 - INFO: 30960099 candidates in all 34187471 reads
> 2020-07-21 17:15:50,209 - INFO: Pre-grouping reads ...
> 2020-07-21 17:15:50,209 - INFO: Setting '--pre-w 116'
> 2020-07-21 17:15:52,872 - INFO: 200000/1003974 used/duplicated
> 2020-07-21 17:16:12,156 - INFO: 4136 groups made.
> 2020-07-21 17:16:17,132 - INFO: Making read index finished.
> 
> 2020-07-21 17:16:17,133 - INFO: Extending ...
> 2020-07-21 17:16:17,133 - INFO: Adding initial words ...
> 2020-07-21 17:16:17,195 - INFO: AW 49052
> 2020-07-21 17:18:27,702 - INFO: Round 1: 30960099/30960099 AI 9911 AW 100560
> 2020-07-21 17:20:41,988 - INFO: Round 2: 30960099/30960099 AI 14248 AW 138194
> 2020-07-21 17:22:50,081 - INFO: Round 3: 30960099/30960099 AI 15433 AW 156064
> 2020-07-21 17:25:10,545 - INFO: Round 4: 30960099/30960099 AI 16081 AW 167542
> 2020-07-21 17:27:31,953 - INFO: Round 5: 30960099/30960099 AI 17687 AW 184372
> 2020-07-21 17:29:48,009 - INFO: Round 6: 30960099/30960099 AI 19228 AW 200436
> 2020-07-21 17:32:04,359 - INFO: Round 7: 30960099/30960099 AI 20364 AW 216006
> 2020-07-21 17:34:23,215 - INFO: Round 8: 30960099/30960099 AI 21622 AW 232268
> 2020-07-21 17:36:48,199 - INFO: Round 9: 30960099/30960099 AI 23430 AW 256698
> 2020-07-21 17:39:09,800 - INFO: Round 10: 30960099/30960099 AI 25249 AW 284960
> 2020-07-21 17:41:31,142 - INFO: Round 11: 30960099/30960099 AI 27303 AW 314488
> 2020-07-21 17:43:51,945 - INFO: Round 12: 30960099/30960099 AI 28837 AW 337984
> 2020-07-21 17:46:16,005 - INFO: Round 13: 30960099/30960099 AI 29801 AW 354218
> 2020-07-21 17:48:35,112 - INFO: Round 14: 30960099/30960099 AI 30560 AW 366176
> 2020-07-21 17:50:49,023 - INFO: Round 15: 30960099/30960099 AI 31155 AW 375604
> 2020-07-21 17:53:05,157 - INFO: Round 16: 30960099/30960099 AI 31585 AW 382226
> 2020-07-21 17:55:21,726 - INFO: Round 17: 30960099/30960099 AI 31774 AW 385998
> 2020-07-21 17:57:42,935 - INFO: Round 18: 30960099/30960099 AI 32054 AW 390454
> 2020-07-21 18:00:09,451 - INFO: Round 19: 30960099/30960099 AI 32307 AW 394340
> 2020-07-21 18:02:35,411 - INFO: Round 20: 30960099/30960099 AI 32730 AW 400198
> 2020-07-21 18:04:56,767 - INFO: Round 21: 30960099/30960099 AI 33106 AW 405490
> 2020-07-21 18:07:16,234 - INFO: Round 22: 30960099/30960099 AI 33331 AW 409536
> 2020-07-21 18:09:36,640 - INFO: Round 23: 30960099/30960099 AI 33592 AW 413208
> 2020-07-21 18:11:53,406 - INFO: Round 24: 30960099/30960099 AI 33837 AW 416380
> 2020-07-21 18:14:05,717 - INFO: Round 25: 30960099/30960099 AI 34055 AW 419710
> 2020-07-21 18:16:18,959 - INFO: Round 26: 30960099/30960099 AI 34396 AW 424514
> 2020-07-21 18:18:31,378 - INFO: Round 27: 30960099/30960099 AI 34659 AW 428078
> 2020-07-21 18:20:44,498 - INFO: Round 28: 30960099/30960099 AI 34929 AW 432170
> 2020-07-21 18:22:57,282 - INFO: Round 29: 30960099/30960099 AI 35128 AW 435348
> 2020-07-21 18:25:10,398 - INFO: Round 30: 30960099/30960099 AI 35578 AW 441468
> 2020-07-21 18:27:22,285 - INFO: Round 31: 30960099/30960099 AI 36045 AW 447784
> 2020-07-21 18:29:37,794 - INFO: Round 32: 30960099/30960099 AI 36288 AW 451720
> 2020-07-21 18:32:04,931 - INFO: Round 33: 30960099/30960099 AI 36438 AW 454300
> 2020-07-21 18:34:28,167 - INFO: Round 34: 30960099/30960099 AI 36605 AW 456692
> 2020-07-21 18:36:42,344 - INFO: Round 35: 30960099/30960099 AI 36850 AW 460434
> 2020-07-21 18:38:56,157 - INFO: Round 36: 30960099/30960099 AI 37122 AW 464976
> 2020-07-21 18:41:14,619 - INFO: Round 37: 30960099/30960099 AI 37298 AW 467784
> 2020-07-21 18:43:41,084 - INFO: Round 38: 30960099/30960099 AI 37404 AW 469582
> 2020-07-21 18:46:07,423 - INFO: Round 39: 30960099/30960099 AI 37543 AW 471286
> 2020-07-21 18:48:30,053 - INFO: Round 40: 30960099/30960099 AI 37798 AW 474110
> 2020-07-21 18:50:50,503 - INFO: Round 41: 30960099/30960099 AI 38030 AW 476488
> 2020-07-21 18:53:13,492 - INFO: Round 42: 30960099/30960099 AI 38070 AW 477100
> 2020-07-21 18:55:36,365 - INFO: Round 43: 30960099/30960099 AI 38127 AW 478000
> 2020-07-21 18:57:56,929 - INFO: Round 44: 30960099/30960099 AI 38330 AW 480744
> 2020-07-21 19:00:20,450 - INFO: Round 45: 30960099/30960099 AI 38607 AW 484336
> 2020-07-21 19:02:47,600 - INFO: Round 46: 30960099/30960099 AI 38984 AW 489700
> 2020-07-21 19:05:11,826 - INFO: Round 47: 30960099/30960099 AI 39379 AW 495220
> 2020-07-21 19:07:35,999 - INFO: Round 48: 30960099/30960099 AI 39718 AW 499892
> 2020-07-21 19:09:57,396 - INFO: Round 49: 30960099/30960099 AI 39975 AW 503412
> 2020-07-21 19:12:12,979 - INFO: Round 50: 30960099/30960099 AI 40273 AW 507324
> 2020-07-21 19:14:34,750 - INFO: Round 51: 30960099/30960099 AI 40420 AW 509332
> 2020-07-21 19:16:55,997 - INFO: Round 52: 30960099/30960099 AI 40559 AW 511434
> 2020-07-21 19:19:22,955 - INFO: Round 53: 30960099/30960099 AI 40676 AW 513330
> 2020-07-21 19:21:47,038 - INFO: Round 54: 30960099/30960099 AI 40723 AW 514038
> 2020-07-21 19:24:13,280 - INFO: Round 55: 30960099/30960099 AI 40738 AW 514328
> 2020-07-21 19:26:41,299 - INFO: Round 56: 30960099/30960099 AI 40740 AW 514336
> 2020-07-21 19:29:07,592 - INFO: Round 57: 30960099/30960099 AI 40801 AW 515170
> 2020-07-21 19:31:31,771 - INFO: Round 58: 30960099/30960099 AI 40859 AW 515992
> 2020-07-21 19:33:50,559 - INFO: Round 59: 30960099/30960099 AI 41042 AW 518264
> 2020-07-21 19:36:09,275 - INFO: Round 60: 30960099/30960099 AI 41242 AW 521350
> 2020-07-21 19:38:27,989 - INFO: Round 61: 30960099/30960099 AI 41436 AW 523988
> 2020-07-21 19:40:46,108 - INFO: Round 62: 30960099/30960099 AI 41529 AW 525788
> 2020-07-21 19:43:05,304 - INFO: Round 63: 30960099/30960099 AI 41621 AW 527462
> 2020-07-21 19:45:24,022 - INFO: Round 64: 30960099/30960099 AI 41684 AW 528500
> 2020-07-21 19:47:43,031 - INFO: Round 65: 30960099/30960099 AI 41722 AW 529068
> 2020-07-21 19:50:02,303 - INFO: Round 66: 30960099/30960099 AI 41752 AW 529626
> 2020-07-21 19:52:20,581 - INFO: Round 67: 30960099/30960099 AI 41785 AW 530088
> 2020-07-21 19:54:39,303 - INFO: Round 68: 30960099/30960099 AI 41815 AW 530706
> 2020-07-21 19:56:57,682 - INFO: Round 69: 30960099/30960099 AI 41842 AW 531130
> 2020-07-21 19:59:16,667 - INFO: Round 70: 30960099/30960099 AI 41920 AW 531934
> 2020-07-21 20:01:35,116 - INFO: Round 71: 30960099/30960099 AI 41957 AW 532308
> 2020-07-21 20:03:53,749 - INFO: Round 72: 30960099/30960099 AI 41971 AW 532512
> 2020-07-21 20:06:11,650 - INFO: Round 73: 30960099/30960099 AI 41984 AW 532822
> 2020-07-21 20:08:31,787 - INFO: Round 74: 30960099/30960099 AI 42015 AW 533280
> 2020-07-21 20:10:50,998 - INFO: Round 75: 30960099/30960099 AI 42082 AW 533840
> 2020-07-21 20:13:09,528 - INFO: Round 76: 30960099/30960099 AI 42146 AW 534820
> 2020-07-21 20:15:28,156 - INFO: Round 77: 30960099/30960099 AI 42228 AW 535958
> 2020-07-21 20:17:46,863 - INFO: Round 78: 30960099/30960099 AI 42276 AW 536592
> 2020-07-21 20:20:05,124 - INFO: Round 79: 30960099/30960099 AI 42313 AW 537282
> 2020-07-21 20:22:23,327 - INFO: Round 80: 30960099/30960099 AI 42378 AW 537910
> 2020-07-21 20:24:41,656 - INFO: Round 81: 30960099/30960099 AI 42405 AW 538412
> 2020-07-21 20:26:59,802 - INFO: Round 82: 30960099/30960099 AI 42426 AW 538698
> 2020-07-21 20:29:18,222 - INFO: Round 83: 30960099/30960099 AI 42463 AW 539278
> 2020-07-21 20:31:36,674 - INFO: Round 84: 30960099/30960099 AI 42522 AW 540100
> 2020-07-21 20:33:55,275 - INFO: Round 85: 30960099/30960099 AI 42561 AW 540928
> 2020-07-21 20:36:13,900 - INFO: Round 86: 30960099/30960099 AI 42597 AW 541548
> 2020-07-21 20:38:32,677 - INFO: Round 87: 30960099/30960099 AI 42609 AW 541738
> 2020-07-21 20:40:52,551 - INFO: Round 88: 30960099/30960099 AI 42613 AW 541832
> 2020-07-21 20:43:11,652 - INFO: Round 89: 30960099/30960099 AI 42617 AW 541920
> 2020-07-21 20:45:31,005 - INFO: Round 90: 30960099/30960099 AI 42617 AW 541920
> 2020-07-21 20:45:31,005 - INFO: No more reads found and terminated ...
> 2020-07-21 20:46:16,339 - INFO: Extending finished.
> 
> 2020-07-21 20:46:16,986 - INFO: Separating filtered fastq file ... 
> 2020-07-21 20:46:17,173 - INFO: Setting '-k 21,55,85,115'
> 2020-07-21 20:46:17,173 - INFO: Assembling using SPAdes ...
> 2020-07-21 20:46:17,227 - INFO: spades.py -t 4  -1 raw_mtgenome/filtered_1_paired.fq -2 raw_mtgenome/filtered_2_paired.fq --s1 raw_mtgenome/filtered_1_unpaired.fq --s2 raw_mtgenome/filtered_2_unpaired.fq -k 21,55,85,115 -o raw_mtgenome/filtered_spades
> 2020-07-21 20:46:35,198 - INFO: Insert size = 209.278, deviation = 59.7293, left quantile = 141, right quantile = 290
> 2020-07-21 20:46:35,198 - INFO: Assembling finished.
> 
> 2020-07-21 20:46:36,956 - **ERROR: Slimming raw_mtgenome/filtered_spades/K115/assembly_graph.fastg failed**.
> 2020-07-21 20:46:37,729 - **ERROR: Slimming raw_mtgenome/filtered_spades/K85/assembly_graph.fastg failed**.
> 2020-07-21 20:46:38,478 - **ERROR: Slimming raw_mtgenome/filtered_spades/K55/assembly_graph.fastg failed**.
> 
> Total cost 13553.32 s
> Thank you!

**Comment by Kinggerm** [comment]
Hi Zexuan,

Sorry for the delay. I just recovered from a cold.
I believe it was the working directory issue. Please don't include "(" or ")" in your working directory.

Please let me know your updates.
Best,
Jianjun

**Comment by Kinggerm** [comment]
Please reopen it if you are still in trouble.
