### ISSUE TITLE
conda install problem

### ISSUE THREAD

**Issue by yanzhongsino** [Kinggerm/GetOrganelle#47]
The command and failure message are following:
$conda install -c bioconda getorganelle
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve.Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
Examining widgetsnbextension:

After updating conda the issue also happen.

Any reply will be welcomed.

**Comment by Kinggerm** [comment]
Could you provide any information about your working environment?

**Comment by Kinggerm** [comment]
I'm closing it because of no reply. Feel free to reopen issue.
