### ISSUE TITLE
Disentangling failed: list index out of range

### ISSUE THREAD

**Issue by agroppi** [Kinggerm/GetOrganelle#5]
I'm trying to assemble the chloroplast of a prunus.
I have set a prunus_cp file in GetOrganelle/Library/SeqReference
and generated the corresponding blast db (makeblastdb in /gpfs/home/ag/GetOrganelle/Library/NotationReference
But i'm facing this error at the desentangling step : 
`Disentangling failed: list index out of range`
Here is the full log  : 
[get_org.log.txt.zip](https://github.com/Kinggerm/GetOrganelle/files/2930353/get_org.log.txt.zip)

**Comment by Kinggerm** [comment]
Hi,

Did you get around the -F restriction by editing get_organelle_reads.py? I think I had made it impossible to use a choice like "prunus_cp". The suggested way for you to use your customized blast db is "-F anonym --genes prunus.genes.fasta -s prunus.fasta". The prunus.genes.fasta is the fasta file you used to make the blast db. For looking into the error you faced, I need the fasta file you used to make the blast db.
Actually, for species within angiosperms, especially for taxa in Rosaceae which I had a bunch of tests, there is generally no need to using a customized blast db. You can easily use the default plant_cp. Let me know if it does not work for you.
Besides, the automatic word size seemed too small for your data. You can try "-w 65" or "-w 71". Since you used a closely related reference, maximum rounds is no need to be 15. You can try "-R 4" or "-R 5".

Let me know the progress!

**Comment by agroppi** [comment]
Hi,
I first try to run the script with the default options and plant_cp : 
```
get_organelle_reads.py \
-t 20 \
-1 reads_1.fq \
-2 reads_2.fq \
-o /outdir \
-R 15 \
-k 75,85,95,105 \
-F plant_cp
```
But the resulting assembly was bad : 
![graph](https://user-images.githubusercontent.com/5609985/53869727-0ed8b300-3ff9-11e9-8ff3-38fd0f0180db.png)

I will try to 
1/ to run the script on plant_cp with w 65 or w 71
2/ to run on prunus_cp by adding the -F option you described

Here is my prunus_cp.fasta
[prunus_cp.zip](https://github.com/Kinggerm/GetOrganelle/files/2935379/prunus_cp.zip)

**Comment by Kinggerm** [comment]
Actually, even if you use the rbcL gene of an angiosperm species _Amborella trichopoda_ (Genbank: NC_005086) as the reference, and try to assemble the dataset sequencing a gymnosperm species _Gnetum gnemon_ (Genbank: ERR268421), you would easily get the right complete circular plastome for _Gnetum gnemon_. We included similar tests on our upcoming paper. I mean if the data is good enough, the reference should have little effects. However, You may still have the chance to find some reads to close the gap with a more closely related reference, although not a big chance. 
If this assembly graph is based on k-mer=95, the base coverage of plastome is really high. It is unusual, but it happens for some data samples (~ 10%). Given this graph, I think you do not need to adjust the -w nor the -R (which is previously suggested for efficiency more than success). You should change the "-k 75,85,95,105" in your options into "-k 35,45,55,65,75".

Let me know the updates!

**Comment by Kinggerm** [comment]
A bit more explanation for using "-F anonym --genes prunus.genes.fasta -s prunus.fasta". (Should be included when preparing for a GetOrganelle manual):

The **prunus.fasta** file followed with "-s" should be a sequence file containing your reference(s). Your prunus_cp.fasta file is just in the right form.

The ***prunus.genes.fasta*, however, should in this form:
>rbcL gene
ATGC
>matK gene
ATGC

**Comment by agroppi** [comment]
I have run the script on plant_cp with 
`-k 35,45,55,65,75`
I have now a lot of warning like this : 
Disentangling failed: Incomplete/Complicated graph

graph in bandage : 
![graph](https://user-images.githubusercontent.com/5609985/53895117-9b06cc80-4031-11e9-8363-c6a44f062a69.png)

Log : 
[get_org.log.txt.zip](https://github.com/Kinggerm/GetOrganelle/files/2937143/get_org.log.txt.zip)

**Comment by Kinggerm** [comment]
Thanks for the graph and log file. There is a big improvement now. Only one break point left (the grey line in the following image).
![53895117-9b06cc80-4031-11e9-8363-c6a44f062a69 modified](https://user-images.githubusercontent.com/8598031/53925862-58d69d00-40bc-11e9-9b74-24d83b05c1e5.png)

You could try 
further decrease the minimum k-mer, such as "**-k 21,35,,45,55,65,75**" and increase the data used by "**--max-reads 3E7**" or larger (default is 1.5E7, that is why "Number of reads exceeded 15000000 in NG-6201_A2067_lib13395_1_sequence.good.fq, only top 15000000 reads are used in downstream analysis" is logged).

**Comment by agroppi** [comment]
results with `-k 21,35,45,55,65,75` and `--max-reads 4E7`

graph : 
![graph](https://user-images.githubusercontent.com/5609985/53966888-660f7e00-40f4-11e9-979b-7211939c2b11.png)
and the log : 
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/2941929/get_org.log.txt)

One last question : 
in the final step I have :  
`WARNING: More than one circular genome structure produced ...`
`WARNING: Please check the final result to confirm whether they are simply flip-flop configurations!`
(PATH1 and  PATH2) 
How can I choose the best one ?

Thanks again

**Comment by Kinggerm** [comment]
Looks great now!
For this graph, they are surely flip-flop configurations ([Walker et al. 2015](https://www.researchgate.net/publication/283576393_Sources_of_inversion_variation_in_the_small_single_copy_SSC_region_of_chloroplast_genomes?_sg=ZGuvLcs7i9W01NLNiAsK7GzPsVTLCo0Eb-yq2vqWJnCWRo4IJ-3Dpd1nr4VebRFEGuFxy1s9Ye-AiQ.YZm8pdJnDHg7gdYEbRL8jC1dpHFxV6Gsr_2JBGO5APNWpvPS5-eqmW9qwNw8ZEN5HMmdlprsE6xxdSkVNZy_tg&_sgd%5Bnc%5D=2&_sgd%5Bncwor%5D=0)). Both of them are right and coexist in plant. For publication, people tend to use just one of them. You can pick the configuration of which the SSC region is in the same direction with most of your data or outgroup, which makes downstream annotation/analysis easier.

Good luck with you study!

**Comment by agroppi** [comment]
Thanks you very much for your help !
I will apply this to chloroplasts close species
