### ISSUE TITLE
the operation is killed before it finshes

### ISSUE THREAD

**Issue by dr-a7madoh** [Kinggerm/GetOrganelle#57]
Dear,
I have been trying to assembly plant mitochondria but the operation always gets killed.

Here I have attached a screenshot of the terminal

Thank you in advance.

<img width="1792" alt="Screenshot 2020-11-03 at 11 34 20" src="https://user-images.githubusercontent.com/58731554/97980342-865f7680-1dc8-11eb-944b-e11a1dc56bca.png">

**Comment by Kinggerm** [comment]
Hi, what's the memory size of your machine?
I guess it's because you were running out of memory.

**Comment by dr-a7madoh** [comment]
Sorry for the last reply,
It is 16 GB.

Thanks

**Comment by Kinggerm** [comment]
16 GB will be too small for mitogenome assembly. You could try a new run with --memory-save, but I guess it's insufficient in following steps.
