### ISSUE TITLE
Reg: Mitochondrial Genome Assembly

### ISSUE THREAD

**Issue by harish0201** [Kinggerm/GetOrganelle#6]
Hi!

We have done an assembly of the mitochondria, but the Bandage plot looks like the following:
![mito](https://user-images.githubusercontent.com/9093815/53932975-56774180-40c2-11e9-90f0-aa222b54f383.png)

Can you suggest a way to filter the same? I did go through your youtube video, wherein you show the duplicate+depth segregation, but I'm unsure for this assembly.

**Comment by Kinggerm** [comment]
Hi!

Generally, for assembling any kind of organelle genome, you have to get the **organelle-sufficient graph**, which I defined to be an assembly graph with contigs completely covers the whole organelle genome. In your case, the assembly graph is not sufficient, meaning that there are about three gaps. Considering the k-mer coverage, this is nice data and it is very likely to get the **mitogenome-sufficient graph** after adjusting some options when running GetOrganelle. Could you please attach the _get_org.log.txt_ file? I can barely tell what to do to improve the assembly graph.

Only when we did obtain **mitogenome-sufficient graph**, we could disentangle the graph into complete sequences. You actually do not need to watch the video and manually disentangle a nice graph like this after you make it "sufficient". You can simply use the script _disentangle_organelle_assembly.py_ (which would be automatically called by the main script). However, for mitogenome with large scale repeats like this graph, there would be lots possible paths, which are potential configurations for the mitogenome, unless you had really long insert size for the sequencing library.

Let's look at the log file first~

**Comment by harish0201** [comment]
Alright! I'm attaching the log-file! I went through the video while going through the paper and I thought it showed good clarity! 

[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/2939863/get_org.log.txt)

Please do let me know, currently I have just used the default parameters with the anti-seed being set as a chloroplast genome

**Comment by Kinggerm** [comment]
I would try using a broader range of k-mer gradient, "-k 21,35,45,55,75,95,105,115,127" first.
You could make a duplicate for previous result and deleted the **filtered_spades** folder and re-run get_organelle_reads.py with your previous options together with "**-k 21,35,45,55,75,95,105,115,127 --continue**", thus the previous extension part would be skipped.

Let me know the progress!

**Comment by harish0201** [comment]
Sure, I'm currently starting the run again.

**Comment by harish0201** [comment]
Hi,

I have finished the run for the same sample using the extended kmer gradient as per your suggestion, I'm also attaching the log file.

![graph](https://user-images.githubusercontent.com/9093815/54111285-8cd9f700-4409-11e9-98af-ab7ae4eb3706.png)

It seems that the graph is still mitogenome-insufficient and as such can't be circularized.

Thanks for the help
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/2955603/get_org.log.txt)

**Comment by Kinggerm** [comment]
Hi,

I mean you should try "-k 21,35,45,55,75,95,105,115,127" rather than 75,85,95,105,115,127 in your log file. Also, you have to delete previous *assembly_graph.fastg* files in the output folder, otherwise the slim & disentangle process would be skipped as well when "--continue" used.
If you cannot quite get the usage of continue, you can start a new run by using:

>get_organelle_reads.py -1 ../../1_R1.clean.fastq -2 ../../1_R2.clean.fastq -s /data/ref_genomes/Eucalyptus_grandis/Eucalyptus_mitochondrion.fasta -a /data/ref_genomes/pomogranate/chloroplast.fasta --genes /data/ref_genomes/Eucalyptus_grandis/Eucalptus_MT_coding_sequnce.fasta -o mitochondria_Sample1 -R 30 -t 20 -k 21,35,45,55,75,95,105,115,127 -F plant_mt

**Comment by harish0201** [comment]
Thank you, I'll do that and get back to you.

**Comment by Kinggerm** [comment]
Since there are no follow-ups, I'm closing this issue. Feel free to reopen it if you have further questions.
