### ISSUE TITLE
--reverse-lsc does not work

### ISSUE THREAD

**Issue by karyowgene** [Kinggerm/GetOrganelle#63]
I have assembled a cp genome but the LSC is in reverse thus making my sequences significantly different from published relatives and hence problematic in downstream processing. I have tried --reverse-lsc option in the get_organelle_from_assembly.py, but the output is just reversed SSC and not LSC. Any help will be highly appreciated. . Attached is the get_org.log.txt
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/5713795/get_org.log.txt)

**Comment by Kinggerm** [comment]
This is covered. Please refer to the [FAQ](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#what-are-the-differences-of-complete1path_sequencefasta-and-complete2path_sequencefasta-output-files) or [issue22](https://github.com/Kinggerm/GetOrganelle/issues/22#issuecomment-542784173).

In short, there are two fasta files. If one is not what you need, the other one should be. But strongly recommend reading the references above.

**Comment by karyowgene** [comment]
Thank you for the prompt response. However, both of the fasta files have the LSC in reverse. One of them has SSC in orientation I want.

**Comment by Kinggerm** [comment]
Oh I see. You are right. It seems that this function's been disabled due to new functions. 
Sorry for that. Gonna fix it soon. I will keep you posted.

**Comment by Kinggerm** [comment]
Thank you for reporting this!
I just fixed this issue. Please update to the latest version (1.7.2b) from Github.
Please let me know the updates.

**Comment by karyowgene** [comment]
Thank you. 
The LSC has been reversed successfully.
