### ISSUE TITLE
Crashes while running GetOrganelle - empty read file

### ISSUE THREAD

**Issue by JUNxjjl** [Kinggerm/GetOrganelle#65]
HI, 

It seems to something missing when I submit the job. The error message shows an empty file in the OUTPUT directory; however, the file's name is the INPUT fasta file. Just wondering if there are some PATH errors or the INPUT files are in the wrong directory??

Thank you a lot.

The log file:
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/5871794/get_org.log.txt)

**Comment by Kinggerm** [comment]
It was because the input Arabidopsis_simulated.1.fq.gz was incomplete. Please re-download it again.
I've attached the md5 values to the example page (https://github.com/Kinggerm/GetOrganelle/wiki/Example-1#quickstart) so that people can be aware of the integrity of the input file.

**Comment by JUNxjjl** [comment]
Thank you for your help!
that is a nice software
