### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by Pgjhmb** [Kinggerm/GetOrganelle#67]
I have conda version 4.2.12 and python 3.5.2 when installing, I get the following error:

UnsatisfiableError: The following specifications were found to be in conflict:
  - getorganelle
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

Dependencies require python >3.

Any rhyme or reason for this?

Thanks

**Comment by Kinggerm** [comment]
Hi, I haven't got into this and don't know the cause. Have you tried creating a new conda environment? e.g. `conda create -n getorganelle python=3.6`, then activate it by `conda activate getorganelle` then do the `conda install` process

**Comment by Pgjhmb** [comment]
The installation process worked, however
Still in the getorganelle conda environment, trying to run get_organelle_config.py --add animal_mt
it returns    get_organelle_config.py: command not found

Nor when trying to run the test: 
get_organelle_from_reads.py -1 Arabidopsis_simulated.1.fq.gz -2 Arabidopsis_simulated.2.fq.gz -t 1 -o Arabidopsis_simulated.plastome -F embplant_pt -R 10

I get the same error

**Comment by Kinggerm** [comment]
It's a rare case and too obscure. Please provide more details, e.g. the installing process and the all associated info.
What did say after `conda install -c bioconda getorganelle`? Is conda already in the $PATH?

**Comment by Pgjhmb** [comment]
It lists the packages as already installed, and conda is already in the $path.

**Comment by Kinggerm** [comment]
I've no clue given the limited info. Maybe try to identify where the trouble is, with GetOrganelle or conda. For example, try to install `bowtie2` (dep of GetOrganelle)? If it is executable, use `which` to locate it, check if it's under conda's env. 

To work around, you can also switch to using the [setup.py](https://github.com/Kinggerm/GetOrganelle/wiki/Installation#option-2-using-the-setuppy)?
