### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by ChenJuiYANG** [Kinggerm/GetOrganelle#68]
I can't install with "conda install -c bioconda getorganelle" 

Here is the following messages returned: 

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__win==0=0:  60%|███████████████████████████████▏                    | 3/5 [00:00<00:00, 11.10it/s]/Examining @/win-64::__archspec==1=x86_64: 100%|██████████████████████████████████████████| 5/5 [00:00<00:00, 12.47it/s]-failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

==end

conda version: 4.9.2

I already updated all the packages and conda version, but it still failed to figure out. 
I also tried to create a new environment, and it still can't work. 

Should I use an older version conda?

Please help to solve this. 
Thanks a lot. 

btw, I am really newbie to command lines.

**Comment by Kinggerm** [comment]
What is the running environment, e.g. Python version and system?

**Comment by ChenJuiYANG** [comment]
Win 10 and environment with Python 3.7.10

**Comment by Kinggerm** [comment]
I'm sorry that GetOrganelle does not support Windows system. You can find info at the homepage or [here](https://github.com/Kinggerm/GetOrganelle/wiki/Installation#requirement--dependencies)

**Comment by ChenJuiYANG** [comment]
Thanks a lot! I didn't notice that...  I will work on Linux system later.
