### ISSUE TITLE
Error with using single end data

### ISSUE THREAD

**Issue by Rbester18** [Kinggerm/GetOrganelle#69]
I have a issue using GetOrganelle with single data (-u option). I get a very general python error: 
TypeError: expected str, bytes or os.PathLike object, not NoneType.
I also tried using the example data as single end, but I get the same error. The paired end Arabidopsis example did run succesfully. Have any one used the single end option successfully or know how to get around this error? My log file is attached.
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/6271976/get_org.log.txt)

**Comment by Kinggerm** [comment]
Hi, it's a bug introduced in a recent update. I just fixed it in latest version, for which you may need to download it by:

    git clone git://github.com/Kinggerm/GetOrganelle --depth=1

and then install it follow [using the setup.py](https://github.com/Kinggerm/GetOrganelle/wiki/Installation#option-2-using-the-setuppy). It will take days for the new version (1.7.4) to be released in conda. Please let me know if you have trouble installing using the setup.py. 

Thanks for the timely bug-report before the release of a new version.

**Comment by Rbester18** [comment]
Thank you for the quick response. Version 1.7.4 works with single end data if I install it with setup.py.

**Comment by Kinggerm** [comment]
Did you mean that it did work, or was that a question?
I will close this issue if it works for you.

**Comment by Rbester18** [comment]
It worked. Thank you very much.
