### ISSUE TITLE
QC trimming for input reads

### ISSUE THREAD

**Issue by akihirao** [Kinggerm/GetOrganelle#78]
Thanks for developing GetOrganelle! Could you tell me whether input reads should be trimmed/filtered to improve the quality prior to analysis?  

Akira

**Comment by Kinggerm** [comment]
I would recommend using adapter-trimmed raw reads without quality control

**Comment by bmelchorcastro** [comment]
Hi, @Kinggerm 
Thanks for developing GetOrganelle. Could you please explain the consequences or expected issues if you do not use adapter-trimmed raw reads?
Bri

**Comment by Kinggerm** [comment]
Untrimmed adapter sequences may be erroneously incorporated into the assembled organelle genomes, creating artificial sequences, gaps, or chimeric assemblies
