### ISSUE TITLE
mixing use of embplant_pt,embplant_mt for algae

### ISSUE THREAD

**Issue by JSSaini** [Kinggerm/GetOrganelle#82]
Each library size is between ~20-25Gb.

Command: ```get_organelle_from_reads.py -1 /home/users/s/saini7/scratch/normalized_reads/Sample_119837/Norm_adapterQcTrimmedFiltered_Sample_119837_R1.fastq
-2 /home/users/s/saini7/scratch/normalized_reads/Sample_119837/Norm_adapterQcTrimmedFiltered_Sample_119837_R2.fastq -o plastome_output -R 30 -k 21,45,65,85,105 -F embplant_pt,embplant_mt --continue -t 2 --memory-save```

Log
 ```plastome_output]$ tail get_org.log.txt
2021-04-30 16:05:47,876 - INFO: Adding initial words ...
2021-04-30 16:05:48,122 - INFO: AW 64860
2021-04-30 16:29:30,161 - INFO: Round 1: 103847608/103847608 AI 7147315 AW 258445398
2021-04-30 16:55:56,806 - INFO: Round 2: 103847608/103847608 AI 18458624 AW 576901890
2021-04-30 17:18:15,997 - INFO: Round 3: 103847608/103847608 AI 28519691 AW 795806578
2021-04-30 17:37:52,726 - INFO: Round 4: 103847608/103847608 AI 37018076 AW 958723982
2021-04-30 17:55:23,445 - INFO: Round 5: 103847608/103847608 AI 43741050 AW 1081909428
2021-04-30 18:10:51,031 - INFO: Round 6: 103847608/103847608 AI 48722308 AW 1172965154
2021-04-30 18:24:43,363 - INFO: Round 7: 103847608/103847608 AI 52275548 AW 1239237826
2021-04-30 18:37:26,353 - INFO: Round 8: 103847608/103847608 AI 54823917 AW 1288422260```


Does getorganelleDB contain databases of algae chloroplasts? Thank you.

**Comment by Kinggerm** [comment]
Please always attach the complete log file for a real troubleshooting.

If you take a look at the [usage](https://github.com/Kinggerm/GetOrganelle/wiki/Usage#main-scripts), the embplant_pt indicates the embryophyte plant plastome, while the algae plastome mode is activated (therefore using default non-embryophyte plant database) by using `-F other_pt`.

I do not recommend using embplant_pt,embplant_mt together in your case, as indicated in the document, which might be computationally more intensive than separate runs.

**Comment by JSSaini** [comment]
Apologies, please see the complete log. Is there any specific database for algae chloroplast and mitochondria hunting? I have my own chloroplast and mitochondria of interest (Fasta), I just don't know how to use this as db to fetch chloroplast and mitochondria of interest from raw reads or assembly. 
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/6409247/get_org.log.txt)

**Comment by Kinggerm** [comment]
You may use the other_pt default, or follow the [FAQ](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#how-to-assemble-a-target-organelle-genome-using-my-own-reference)

**Comment by JSSaini** [comment]
Hi, Thank you for your kind assistance. Just a quick question:


How can I give input of algae specific mitochondrial database (For example; other_mt)?


________________________________

**Comment by Kinggerm** [comment]
There's currently no built-in non-embryophyte mt database. However, there are a few instances from the users that the embplant_mt worked for non-embryophyte mt. You may also use `-F embplant_mt` but with your own database (-s, --genes).

Again, I would recommend running `other_pt` and `embplant_mt` separately for you (and most) samples.

**Comment by Kinggerm** [comment]
The target coverage seems low (pre-assembly estimation may not be very accurate though), which is why it took so much computational resources and why there is little hope for complete mt genome.
What I will do is, waiting for the run to finish, meanwhile trying another run with your own database (-s, --genes).
