### ISSUE TITLE
Insufficient organelle graph or disentangling timeout

### ISSUE THREAD

**Issue by joselatrans** [Kinggerm/GetOrganelle#84]
Hi, I'm running your program to get a plastome from reads. It said it timed-out so I ran it again with more time for disentangling and it said the graph was insufficient, then I ran an assembly and tried get_organelle_from_assembly and still no genome with sufficient graph was obtained.

Here are the logs and graphs:

- From reads (disentangling timeout)

[get_org.log_2.txt](https://github.com/Kinggerm/GetOrganelle/files/6432665/get_org.log_2.txt)
![graph_2](https://user-images.githubusercontent.com/24509090/117262079-2b7b0a80-ae51-11eb-9564-8f2ccec36655.png)

-From reads with disentangling time limit set to 7200

[get_org.log_3.txt](https://github.com/Kinggerm/GetOrganelle/files/6432666/get_org.log_3.txt)
![graph_3](https://user-images.githubusercontent.com/24509090/117265297-629eeb00-ae54-11eb-84af-196406864fcb.png)

- From assembly

[get_org.log_fromAssembly.txt](https://github.com/Kinggerm/GetOrganelle/files/6432668/get_org.log_fromAssembly.txt)

The graph was bigger and took too long to load.

What do you think I could do next to resolve it?

Also, I still don't understand how editing the graphs will result in improving the fasta.

Best, 

José

**Comment by Kinggerm** [comment]
You may not able to obtain the complete plastome from based this sample.

Firstly, the overall plastome coverage is relatively low, leading to insufficient graph. Secondly, the mt and pt have many shared contigs and almost the same coverage, making it hard to distinguish them from each other. You many blast all contigs (in the upper graph) against the genbank online database to better identify the target type, manually remove the mt contigs, and use the remaining contigs as the your incomplete assembly for downstream analysis.

**Comment by joselatrans** [comment]
Ok, I'll give that a try. But it's true it might be a problem with the dataset.
Thanks
