### ISSUE TITLE
bowtie2 cannot be found

### ISSUE THREAD

**Issue by yergol** [Kinggerm/GetOrganelle#85]
Hi! When I try to  initialize the databases, I get  ERROR: Bowtie2 is not available! , even though it is available in the environment. I'm sort of new to Linux. What could be the possible problems that I miss?

Best, 
Yeliz

**Comment by Kinggerm** [comment]
Are you able to run bowtie2 in the terminal? What did you get if you type in `bowtie2 --help`?

Also, please provide more information of the environment, e.g. GetOrganelle version, system info, etc.

**Comment by yergol** [comment]
I couldn't run bowtie2 in terminal. I got the error below 
 when I typed help command. /okyanus/users/yergol/.conda/envs/yeliz/bin/bowtie2-align-s: symbol lookup error: /okyanus/users/yergol/.conda/envs/yeliz/bin/bowtie2-align-s: undefined symbol: _ZN3tbb10interface78internal15task_arena_base19internal_initializeEv
(ERR): Description of arguments failed!
Exiting now ...
I use Linux CentOs 7 system and Anaconda 3.5.3 with Python 3.7.1. for GetOrganelle v1.74.1. 

Thank you for your help!

**Comment by Kinggerm** [comment]
I believe it's the error with some deps of bowtie2.

I found this. https://github.com/BenLangmead/bowtie2/issues/336
You may try the solutions there.

Please let me know if it works for you or not.

**Comment by yergol** [comment]
I solved it with the suggestions in the link you shared. 

Thanks a lot!

King Regard,
Yeliz

**Comment by Kinggerm** [comment]
Current solution: 

`conda install tbb=2020.2`
