### ISSUE TITLE
GetOrganelle组装裸子植物组装不出来

### ISSUE THREAD

**Issue by 15099260779** [Kinggerm/GetOrganelle#88]
我们使用GetOrganelle组装裸子植物（松属）组装不出来，Bandage手动矫正图如附件，矫正删减可以成环但是基因组大小只有正常基因组NCBI上同种的一半大小。怀疑是不是跟被子植物和裸子植物类型有关？（备注：课题组使用该软件以往都是组装被子植物的，从未组装过裸子植物。）
[Bandage Graph.docx](https://github.com/Kinggerm/GetOrganelle/files/6680573/Bandage.Graph.docx)
e Graph.docx…]()

**Comment by Kinggerm** [comment]
Please always attach the log file before posting any case-based questions or issues.

We have included gymnosperm runs in our benchmarking test: https://github.com/Kinggerm/GetOrganelleComparison

You should NEVER do what you did for generating the so-called circular result. We (at least I personally) never advocate users to prune contigs like this. If you did similar thing for previous runs, discard all associated results. 

There are generally two reasons for the tangled assembly graph (and multiple paths) output of Pinaceae samples. The first is that there may be isomers (biological reason); the second is that there are short repeats with length longer than the kmer (methodological reason).

**Comment by 15099260779** [comment]
The chloroplast genome of Pinus species has a short repeat region, and a repeat region is lost. Based on the above two reasons you mentioned, I think it should be the second one. What should I do to solve the problem?

**Comment by Kinggerm** [comment]
Please read my comments carefully, otherwise no further comments.

**Comment by 15099260779** [comment]
The maximum KMER value I used before was 105. Can I adjust the KMER value to be greater than 105
