### ISSUE TITLE
ERROR - ValueError

### ISSUE THREAD

**Issue by BoHyeonPark** [Kinggerm/GetOrganelle#89]
Hi, I analyzed the Illumina paired-end fastq files. (Input files)
But, I got some errors as below. I think the tool can't read the input file.
Could you tell me the solution?
I attached get_org_log.txt file. Please refer to it.

GetOrganelle v1.7.4.1

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.7.6 (default, Jan  8 2020, 19:59:22)  [GCC 7.3.0]
PLATFORM: Linux ip-172-31-10-46.us-east-2.compute.internal 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64
PYTHON LIBS: GetOrganelleLib 1.7.4.1; numpy 1.18.1; sympy 1.5.1; scipy 1.4.1; psutil 5.6.7
DEPENDENCIES: Bowtie2 2.3.5.1; SPAdes 3.13.0; Blast 2.5.0
GETORG_PATH=/home/centos/.GetOrganelle
LABEL DB: embplant_pt 0.0.1; embplant_mt 0.0.1
WORKING DIR: /home/centos/CP_assembly
/home/centos/anaconda3/bin/get_organelle_from_reads.py -1 /home/centos/CP_assembly/CP_1.fastq.gz -2 /home/centos/CP_assembly/CP_2.fastq.gz -t 15 -o CP.plastome -F embplant_pt -R 10 -s /home/centos/CP_assembly/seed/cp_ref.fasta

2021-07-01 04:28:06,137 - INFO: Pre-reading fastq ...
2021-07-01 04:28:06,137 - INFO: Estimating reads to use ... (to use all reads, set '--reduce-reads-for-coverage inf --max-reads inf')
2021-07-01 04:28:06,211 - INFO: Tasting 100000+100000 reads ...
2021-07-01 04:28:06,218 - ERROR: 
Traceback (most recent call last):
  File "/home/centos/anaconda3/bin/get_organelle_from_reads.py", line 3880, in main
    random_seed=options.random_seed, verbose_log=options.verbose_log, log_handler=log_handler)
  File "/home/centos/anaconda3/bin/get_organelle_from_reads.py", line 1076, in estimate_maximum_n_reads_using_mapping
    raise ValueError("Empty file" + check_fq + "\n"
ValueError: Empty fileCP.plastome/check/1/check_1
Please check the legality and integrity of your input reads!

Total cost 0.91 s
Please email jianjun.jin@columbia.edu and jinjianjun@mail.kib.ac.cn if you find bugs!
Please provide me with the get_org.log.txt file!

**Comment by Kinggerm** [comment]
This error should be caused by damaged fastq files.

Try to do as the log says to check your input file. You can try the [example](https://github.com/Kinggerm/GetOrganelle/wiki/Example-1) first, there's a `md5` check process in it, which checks the file before and after downloading.

**Comment by BoHyeonPark** [comment]
As you said, I checked the md5sum, and the fastq files was damaged. 
I downloaded the raw data again and am checking it. Thank you for your reply.
