### ISSUE TITLE
4 FASTQ files

### ISSUE THREAD

**Issue by Dra7madoh** [Kinggerm/GetOrganelle#90]
Dear,

I have received 4 different 4 fastq files for my sample from novogene. My question is, how can I run the assembly for all of them combined? I need to run mtDNA and cpDNA.

Thank you

**Comment by Kinggerm** [comment]
You may either
1) run one pair first to see if the estimated coverage is enough, 
    
    get_organelle_from_reads.py  -1 readA_1.fq -2 readA_2.fq ..

2) or combine the unzipped fastq files into a pair using 
    
    cat *_1.fq > combined_1.fq
    cat *_2.fq > combined_2.fq
    get_organelle_from_reads.py -1 combined_1.fq -2 combined_2.fq ..

3) or input the first pair as paired and latter files as unpaired, e.g. 

   get_organelle_from_reads.py -1 readA_1.fq -2 readA_2.fq -u readB_1.fq,readB_2.fq ..
