### ISSUE TITLE
Skipping/optimizing read search

### ISSUE THREAD

**Issue by sivico26** [Kinggerm/GetOrganelle#96]
Hi there,

I would like to ask you if it is possible to skip the first part of the pipeline (the search for organellar reads).

Here is my case: I have already rescued the organellar reads from a big pool. I know `GetOrganlle` can do this, but I need to boost the performance so I am doing it with other tools. Now, I want to assemble with GetOrganelle, but I do not need him to try to search for the appropriate reads in the pool I am giving to him. I am sure he would notice quickly but it is inefficient to search twice.

So, my question is: is there a way to tell `GetOrganelle` to skip the search and go directly to the assembly step with the provided data?

I have had some success assembling the aforementioned pool of reads with plasmid `Spades` (and Spades) and then used `get_organelle_from_assembly` to generate the circular molecule. However, it would be nice to just use GetOrganelle for the assembly as well, instead of using two assemblers.

I would appreciate your thoughts on this. 
Cheers,

**Comment by Kinggerm** [comment]
The way of using `SPAdes` then `get_organelle_from_assembly` will be my current suggestion.

I will take your demand into consideration for next updates, e.g. using one option to skip the reads recruitment process.

**Comment by sivico26** [comment]
Thanks for the quick reply and clarification. Let me know if it indeed ends up in the pipeline!

Cheers
