### ISSUE TITLE
How to use "-s" and "--genes"?

### ISSUE THREAD

**Issue by xiaomeiqiu-biology** [Kinggerm/GetOrganelle#98]
I I have my own SeedDatabase and LabelDatabase, but when I run, it display error:
 
get_organelle_from_reads.py: error: unrecognized arguments: –s *.fasta

What's wrong? Request to solve!

**Comment by Kinggerm** [comment]
Please describe how you made and used your customized database in detail

**Comment by xiaomeiqiu-biology** [comment]
I made my own reference database(CSC_cds.fasta and CSC.fasta, download the genbank format from NCBI database) according to the format of GetOrganelleDB/0.0.1.

Then, I ran the command: 
get_organelle_from_reads.py -1 1_clean.fa -2 2_clean.fa -o COL_plastome -R 15 -k 21,45,65,85,105 -s CSC.fasta --genes CSC_cds.fasta

**Comment by Kinggerm** [comment]
This looks standard.

I noticed that your error was:
>get_organelle_from_reads.py: error: unrecognized arguments: –s *.fasta

with the dash before `s` being `–` not `-`, could that be the reason?

**Comment by xiaomeiqiu-biology** [comment]
Yes，I try to use --s *.fasta, and now it can run smoothly. Thank you!

**Comment by Kinggerm** [comment]
It does not need to be `--s`. It could be `-s`, but not `–s`. The key point here is that `–` is different from `-`.
